/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from '@prisma/client/runtime/client'
import * as $Enums from './enums.js'
import * as $Class from './internal/class.js'
import * as Prisma from './internal/prismaNamespace.js'

export * as $Enums from './enums.js'
export * from './enums.js'
/**
 * ## Prisma Client
 *
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient({
 *   adapter: new PrismaPg({ connectionString: process.env.DATABASE_URL })
 * })
 * // Fetch zero or more Blog_comments
 * const blog_comments = await prisma.blog_comment.findMany()
 * ```
 *
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<
  LogOpts extends Prisma.LogLevel = never,
  OmitOpts extends Prisma.PrismaClientOptions['omit'] =
    Prisma.PrismaClientOptions['omit'],
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model blog_comment
 *
 */
export type blog_comment = Prisma.blog_commentModel
/**
 * Model blog_like
 *
 */
export type blog_like = Prisma.blog_likeModel
/**
 * Model blog_view
 *
 */
export type blog_view = Prisma.blog_viewModel
/**
 * Model essay
 *
 */
export type essay = Prisma.essayModel
/**
 * Model qq_content
 *
 */
export type qq_content = Prisma.qq_contentModel
