/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `blog_like` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums.js'
import type * as Prisma from '../internal/prismaNamespace.js'

/**
 * Model blog_like
 *
 */
export type blog_likeModel =
  runtime.Types.Result.DefaultSelection<Prisma.$blog_likePayload>

export type AggregateBlog_like = {
  _count: Blog_likeCountAggregateOutputType | null
  _avg: Blog_likeAvgAggregateOutputType | null
  _sum: Blog_likeSumAggregateOutputType | null
  _min: Blog_likeMinAggregateOutputType | null
  _max: Blog_likeMaxAggregateOutputType | null
}

export type Blog_likeAvgAggregateOutputType = {
  user_id: number | null
}

export type Blog_likeSumAggregateOutputType = {
  user_id: bigint | null
}

export type Blog_likeMinAggregateOutputType = {
  id: string | null
  file_id: string | null
  user_id: bigint | null
  created_at: Date | null
}

export type Blog_likeMaxAggregateOutputType = {
  id: string | null
  file_id: string | null
  user_id: bigint | null
  created_at: Date | null
}

export type Blog_likeCountAggregateOutputType = {
  id: number
  file_id: number
  user_id: number
  created_at: number
  _all: number
}

export type Blog_likeAvgAggregateInputType = {
  user_id?: true
}

export type Blog_likeSumAggregateInputType = {
  user_id?: true
}

export type Blog_likeMinAggregateInputType = {
  id?: true
  file_id?: true
  user_id?: true
  created_at?: true
}

export type Blog_likeMaxAggregateInputType = {
  id?: true
  file_id?: true
  user_id?: true
  created_at?: true
}

export type Blog_likeCountAggregateInputType = {
  id?: true
  file_id?: true
  user_id?: true
  created_at?: true
  _all?: true
}

export type Blog_likeAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which blog_like to aggregate.
   */
  where?: Prisma.blog_likeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of blog_likes to fetch.
   */
  orderBy?:
    | Prisma.blog_likeOrderByWithRelationInput
    | Prisma.blog_likeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.blog_likeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` blog_likes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` blog_likes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned blog_likes
   **/
  _count?: true | Blog_likeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: Blog_likeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: Blog_likeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: Blog_likeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: Blog_likeMaxAggregateInputType
}

export type GetBlog_likeAggregateType<T extends Blog_likeAggregateArgs> = {
  [P in keyof T & keyof AggregateBlog_like]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBlog_like[P]>
    : Prisma.GetScalarType<T[P], AggregateBlog_like[P]>
}

export type blog_likeGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.blog_likeWhereInput
  orderBy?:
    | Prisma.blog_likeOrderByWithAggregationInput
    | Prisma.blog_likeOrderByWithAggregationInput[]
  by: Prisma.Blog_likeScalarFieldEnum[] | Prisma.Blog_likeScalarFieldEnum
  having?: Prisma.blog_likeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Blog_likeCountAggregateInputType | true
  _avg?: Blog_likeAvgAggregateInputType
  _sum?: Blog_likeSumAggregateInputType
  _min?: Blog_likeMinAggregateInputType
  _max?: Blog_likeMaxAggregateInputType
}

export type Blog_likeGroupByOutputType = {
  id: string
  file_id: string
  user_id: bigint
  created_at: Date
  _count: Blog_likeCountAggregateOutputType | null
  _avg: Blog_likeAvgAggregateOutputType | null
  _sum: Blog_likeSumAggregateOutputType | null
  _min: Blog_likeMinAggregateOutputType | null
  _max: Blog_likeMaxAggregateOutputType | null
}

export type GetBlog_likeGroupByPayload<T extends blog_likeGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<Blog_likeGroupByOutputType, T['by']> & {
        [P in keyof T & keyof Blog_likeGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Blog_likeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Blog_likeGroupByOutputType[P]>
      }
    >
  >

export type blog_likeWhereInput = {
  AND?: Prisma.blog_likeWhereInput | Prisma.blog_likeWhereInput[]
  OR?: Prisma.blog_likeWhereInput[]
  NOT?: Prisma.blog_likeWhereInput | Prisma.blog_likeWhereInput[]
  id?: Prisma.StringFilter<'blog_like'> | string
  file_id?: Prisma.StringFilter<'blog_like'> | string
  user_id?: Prisma.BigIntFilter<'blog_like'> | bigint | number
  created_at?: Prisma.DateTimeFilter<'blog_like'> | Date | string
}

export type blog_likeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  file_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _relevance?: Prisma.blog_likeOrderByRelevanceInput
}

export type blog_likeWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    file_id_user_id?: Prisma.blog_likeFile_idUser_idCompoundUniqueInput
    AND?: Prisma.blog_likeWhereInput | Prisma.blog_likeWhereInput[]
    OR?: Prisma.blog_likeWhereInput[]
    NOT?: Prisma.blog_likeWhereInput | Prisma.blog_likeWhereInput[]
    file_id?: Prisma.StringFilter<'blog_like'> | string
    user_id?: Prisma.BigIntFilter<'blog_like'> | bigint | number
    created_at?: Prisma.DateTimeFilter<'blog_like'> | Date | string
  },
  'id' | 'file_id_user_id'
>

export type blog_likeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  file_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.blog_likeCountOrderByAggregateInput
  _avg?: Prisma.blog_likeAvgOrderByAggregateInput
  _max?: Prisma.blog_likeMaxOrderByAggregateInput
  _min?: Prisma.blog_likeMinOrderByAggregateInput
  _sum?: Prisma.blog_likeSumOrderByAggregateInput
}

export type blog_likeScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.blog_likeScalarWhereWithAggregatesInput
    | Prisma.blog_likeScalarWhereWithAggregatesInput[]
  OR?: Prisma.blog_likeScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.blog_likeScalarWhereWithAggregatesInput
    | Prisma.blog_likeScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<'blog_like'> | string
  file_id?: Prisma.StringWithAggregatesFilter<'blog_like'> | string
  user_id?: Prisma.BigIntWithAggregatesFilter<'blog_like'> | bigint | number
  created_at?: Prisma.DateTimeWithAggregatesFilter<'blog_like'> | Date | string
}

export type blog_likeCreateInput = {
  id: string
  file_id: string
  user_id: bigint | number
  created_at?: Date | string
}

export type blog_likeUncheckedCreateInput = {
  id: string
  file_id: string
  user_id: bigint | number
  created_at?: Date | string
}

export type blog_likeUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  file_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type blog_likeUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  file_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type blog_likeCreateManyInput = {
  id: string
  file_id: string
  user_id: bigint | number
  created_at?: Date | string
}

export type blog_likeUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  file_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type blog_likeUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  file_id?: Prisma.StringFieldUpdateOperationsInput | string
  user_id?: Prisma.BigIntFieldUpdateOperationsInput | bigint | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type blog_likeOrderByRelevanceInput = {
  fields:
    | Prisma.blog_likeOrderByRelevanceFieldEnum
    | Prisma.blog_likeOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type blog_likeFile_idUser_idCompoundUniqueInput = {
  file_id: string
  user_id: bigint | number
}

export type blog_likeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  file_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type blog_likeAvgOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
}

export type blog_likeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  file_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type blog_likeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  file_id?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type blog_likeSumOrderByAggregateInput = {
  user_id?: Prisma.SortOrder
}

export type blog_likeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    file_id?: boolean
    user_id?: boolean
    created_at?: boolean
  },
  ExtArgs['result']['blog_like']
>

export type blog_likeSelectScalar = {
  id?: boolean
  file_id?: boolean
  user_id?: boolean
  created_at?: boolean
}

export type blog_likeOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'file_id' | 'user_id' | 'created_at',
  ExtArgs['result']['blog_like']
>

export type $blog_likePayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'blog_like'
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      file_id: string
      user_id: bigint
      created_at: Date
    },
    ExtArgs['result']['blog_like']
  >
  composites: {}
}

export type blog_likeGetPayload<
  S extends boolean | null | undefined | blog_likeDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$blog_likePayload, S>

export type blog_likeCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<blog_likeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: Blog_likeCountAggregateInputType | true
}

export interface blog_likeDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['blog_like']
    meta: { name: 'blog_like' }
  }
  /**
   * Find zero or one Blog_like that matches the filter.
   * @param {blog_likeFindUniqueArgs} args - Arguments to find a Blog_like
   * @example
   * // Get one Blog_like
   * const blog_like = await prisma.blog_like.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends blog_likeFindUniqueArgs>(
    args: Prisma.SelectSubset<T, blog_likeFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__blog_likeClient<
    runtime.Types.Result.GetResult<
      Prisma.$blog_likePayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one Blog_like that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {blog_likeFindUniqueOrThrowArgs} args - Arguments to find a Blog_like
   * @example
   * // Get one Blog_like
   * const blog_like = await prisma.blog_like.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends blog_likeFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, blog_likeFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__blog_likeClient<
    runtime.Types.Result.GetResult<
      Prisma.$blog_likePayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Blog_like that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {blog_likeFindFirstArgs} args - Arguments to find a Blog_like
   * @example
   * // Get one Blog_like
   * const blog_like = await prisma.blog_like.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends blog_likeFindFirstArgs>(
    args?: Prisma.SelectSubset<T, blog_likeFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__blog_likeClient<
    runtime.Types.Result.GetResult<
      Prisma.$blog_likePayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Blog_like that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {blog_likeFindFirstOrThrowArgs} args - Arguments to find a Blog_like
   * @example
   * // Get one Blog_like
   * const blog_like = await prisma.blog_like.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends blog_likeFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, blog_likeFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__blog_likeClient<
    runtime.Types.Result.GetResult<
      Prisma.$blog_likePayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more Blog_likes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {blog_likeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Blog_likes
   * const blog_likes = await prisma.blog_like.findMany()
   *
   * // Get first 10 Blog_likes
   * const blog_likes = await prisma.blog_like.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const blog_likeWithIdOnly = await prisma.blog_like.findMany({ select: { id: true } })
   *
   */
  findMany<T extends blog_likeFindManyArgs>(
    args?: Prisma.SelectSubset<T, blog_likeFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$blog_likePayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a Blog_like.
   * @param {blog_likeCreateArgs} args - Arguments to create a Blog_like.
   * @example
   * // Create one Blog_like
   * const Blog_like = await prisma.blog_like.create({
   *   data: {
   *     // ... data to create a Blog_like
   *   }
   * })
   *
   */
  create<T extends blog_likeCreateArgs>(
    args: Prisma.SelectSubset<T, blog_likeCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__blog_likeClient<
    runtime.Types.Result.GetResult<
      Prisma.$blog_likePayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many Blog_likes.
   * @param {blog_likeCreateManyArgs} args - Arguments to create many Blog_likes.
   * @example
   * // Create many Blog_likes
   * const blog_like = await prisma.blog_like.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends blog_likeCreateManyArgs>(
    args?: Prisma.SelectSubset<T, blog_likeCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Blog_like.
   * @param {blog_likeDeleteArgs} args - Arguments to delete one Blog_like.
   * @example
   * // Delete one Blog_like
   * const Blog_like = await prisma.blog_like.delete({
   *   where: {
   *     // ... filter to delete one Blog_like
   *   }
   * })
   *
   */
  delete<T extends blog_likeDeleteArgs>(
    args: Prisma.SelectSubset<T, blog_likeDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__blog_likeClient<
    runtime.Types.Result.GetResult<
      Prisma.$blog_likePayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one Blog_like.
   * @param {blog_likeUpdateArgs} args - Arguments to update one Blog_like.
   * @example
   * // Update one Blog_like
   * const blog_like = await prisma.blog_like.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends blog_likeUpdateArgs>(
    args: Prisma.SelectSubset<T, blog_likeUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__blog_likeClient<
    runtime.Types.Result.GetResult<
      Prisma.$blog_likePayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more Blog_likes.
   * @param {blog_likeDeleteManyArgs} args - Arguments to filter Blog_likes to delete.
   * @example
   * // Delete a few Blog_likes
   * const { count } = await prisma.blog_like.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends blog_likeDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, blog_likeDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Blog_likes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {blog_likeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Blog_likes
   * const blog_like = await prisma.blog_like.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends blog_likeUpdateManyArgs>(
    args: Prisma.SelectSubset<T, blog_likeUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Blog_like.
   * @param {blog_likeUpsertArgs} args - Arguments to update or create a Blog_like.
   * @example
   * // Update or create a Blog_like
   * const blog_like = await prisma.blog_like.upsert({
   *   create: {
   *     // ... data to create a Blog_like
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Blog_like we want to update
   *   }
   * })
   */
  upsert<T extends blog_likeUpsertArgs>(
    args: Prisma.SelectSubset<T, blog_likeUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__blog_likeClient<
    runtime.Types.Result.GetResult<
      Prisma.$blog_likePayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of Blog_likes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {blog_likeCountArgs} args - Arguments to filter Blog_likes to count.
   * @example
   * // Count the number of Blog_likes
   * const count = await prisma.blog_like.count({
   *   where: {
   *     // ... the filter for the Blog_likes we want to count
   *   }
   * })
   **/
  count<T extends blog_likeCountArgs>(
    args?: Prisma.Subset<T, blog_likeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Blog_likeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Blog_like.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Blog_likeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends Blog_likeAggregateArgs>(
    args: Prisma.Subset<T, Blog_likeAggregateArgs>,
  ): Prisma.PrismaPromise<GetBlog_likeAggregateType<T>>

  /**
   * Group by Blog_like.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {blog_likeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends blog_likeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends (Prisma.True extends HasSelectOrTake
      ? { orderBy: blog_likeGroupByArgs['orderBy'] }
      : { orderBy?: blog_likeGroupByArgs['orderBy'] }),
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends (T['by'] extends never[] ? Prisma.True : Prisma.False),
    InputErrors extends (ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    'Field ',
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]),
  >(
    args: Prisma.SubsetIntersection<T, blog_likeGroupByArgs, OrderByArg> &
      InputErrors,
  ): {} extends InputErrors
    ? GetBlog_likeGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the blog_like model
   */
  readonly fields: blog_likeFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for blog_like.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__blog_likeClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the blog_like model
 */
export interface blog_likeFieldRefs {
  readonly id: Prisma.FieldRef<'blog_like', 'String'>
  readonly file_id: Prisma.FieldRef<'blog_like', 'String'>
  readonly user_id: Prisma.FieldRef<'blog_like', 'BigInt'>
  readonly created_at: Prisma.FieldRef<'blog_like', 'DateTime'>
}

// Custom InputTypes
/**
 * blog_like findUnique
 */
export type blog_likeFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the blog_like
   */
  select?: Prisma.blog_likeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the blog_like
   */
  omit?: Prisma.blog_likeOmit<ExtArgs> | null
  /**
   * Filter, which blog_like to fetch.
   */
  where: Prisma.blog_likeWhereUniqueInput
}

/**
 * blog_like findUniqueOrThrow
 */
export type blog_likeFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the blog_like
   */
  select?: Prisma.blog_likeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the blog_like
   */
  omit?: Prisma.blog_likeOmit<ExtArgs> | null
  /**
   * Filter, which blog_like to fetch.
   */
  where: Prisma.blog_likeWhereUniqueInput
}

/**
 * blog_like findFirst
 */
export type blog_likeFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the blog_like
   */
  select?: Prisma.blog_likeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the blog_like
   */
  omit?: Prisma.blog_likeOmit<ExtArgs> | null
  /**
   * Filter, which blog_like to fetch.
   */
  where?: Prisma.blog_likeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of blog_likes to fetch.
   */
  orderBy?:
    | Prisma.blog_likeOrderByWithRelationInput
    | Prisma.blog_likeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for blog_likes.
   */
  cursor?: Prisma.blog_likeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` blog_likes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` blog_likes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of blog_likes.
   */
  distinct?: Prisma.Blog_likeScalarFieldEnum | Prisma.Blog_likeScalarFieldEnum[]
}

/**
 * blog_like findFirstOrThrow
 */
export type blog_likeFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the blog_like
   */
  select?: Prisma.blog_likeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the blog_like
   */
  omit?: Prisma.blog_likeOmit<ExtArgs> | null
  /**
   * Filter, which blog_like to fetch.
   */
  where?: Prisma.blog_likeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of blog_likes to fetch.
   */
  orderBy?:
    | Prisma.blog_likeOrderByWithRelationInput
    | Prisma.blog_likeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for blog_likes.
   */
  cursor?: Prisma.blog_likeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` blog_likes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` blog_likes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of blog_likes.
   */
  distinct?: Prisma.Blog_likeScalarFieldEnum | Prisma.Blog_likeScalarFieldEnum[]
}

/**
 * blog_like findMany
 */
export type blog_likeFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the blog_like
   */
  select?: Prisma.blog_likeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the blog_like
   */
  omit?: Prisma.blog_likeOmit<ExtArgs> | null
  /**
   * Filter, which blog_likes to fetch.
   */
  where?: Prisma.blog_likeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of blog_likes to fetch.
   */
  orderBy?:
    | Prisma.blog_likeOrderByWithRelationInput
    | Prisma.blog_likeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing blog_likes.
   */
  cursor?: Prisma.blog_likeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` blog_likes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` blog_likes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of blog_likes.
   */
  distinct?: Prisma.Blog_likeScalarFieldEnum | Prisma.Blog_likeScalarFieldEnum[]
}

/**
 * blog_like create
 */
export type blog_likeCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the blog_like
   */
  select?: Prisma.blog_likeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the blog_like
   */
  omit?: Prisma.blog_likeOmit<ExtArgs> | null
  /**
   * The data needed to create a blog_like.
   */
  data: Prisma.XOR<
    Prisma.blog_likeCreateInput,
    Prisma.blog_likeUncheckedCreateInput
  >
}

/**
 * blog_like createMany
 */
export type blog_likeCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many blog_likes.
   */
  data: Prisma.blog_likeCreateManyInput | Prisma.blog_likeCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * blog_like update
 */
export type blog_likeUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the blog_like
   */
  select?: Prisma.blog_likeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the blog_like
   */
  omit?: Prisma.blog_likeOmit<ExtArgs> | null
  /**
   * The data needed to update a blog_like.
   */
  data: Prisma.XOR<
    Prisma.blog_likeUpdateInput,
    Prisma.blog_likeUncheckedUpdateInput
  >
  /**
   * Choose, which blog_like to update.
   */
  where: Prisma.blog_likeWhereUniqueInput
}

/**
 * blog_like updateMany
 */
export type blog_likeUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update blog_likes.
   */
  data: Prisma.XOR<
    Prisma.blog_likeUpdateManyMutationInput,
    Prisma.blog_likeUncheckedUpdateManyInput
  >
  /**
   * Filter which blog_likes to update
   */
  where?: Prisma.blog_likeWhereInput
  /**
   * Limit how many blog_likes to update.
   */
  limit?: number
}

/**
 * blog_like upsert
 */
export type blog_likeUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the blog_like
   */
  select?: Prisma.blog_likeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the blog_like
   */
  omit?: Prisma.blog_likeOmit<ExtArgs> | null
  /**
   * The filter to search for the blog_like to update in case it exists.
   */
  where: Prisma.blog_likeWhereUniqueInput
  /**
   * In case the blog_like found by the `where` argument doesn't exist, create a new blog_like with this data.
   */
  create: Prisma.XOR<
    Prisma.blog_likeCreateInput,
    Prisma.blog_likeUncheckedCreateInput
  >
  /**
   * In case the blog_like was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.blog_likeUpdateInput,
    Prisma.blog_likeUncheckedUpdateInput
  >
}

/**
 * blog_like delete
 */
export type blog_likeDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the blog_like
   */
  select?: Prisma.blog_likeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the blog_like
   */
  omit?: Prisma.blog_likeOmit<ExtArgs> | null
  /**
   * Filter which blog_like to delete.
   */
  where: Prisma.blog_likeWhereUniqueInput
}

/**
 * blog_like deleteMany
 */
export type blog_likeDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which blog_likes to delete
   */
  where?: Prisma.blog_likeWhereInput
  /**
   * Limit how many blog_likes to delete.
   */
  limit?: number
}

/**
 * blog_like without action
 */
export type blog_likeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the blog_like
   */
  select?: Prisma.blog_likeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the blog_like
   */
  omit?: Prisma.blog_likeOmit<ExtArgs> | null
}
