/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `essay` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums.js'
import type * as Prisma from '../internal/prismaNamespace.js'

/**
 * Model essay
 *
 */
export type essayModel =
  runtime.Types.Result.DefaultSelection<Prisma.$essayPayload>

export type AggregateEssay = {
  _count: EssayCountAggregateOutputType | null
  _min: EssayMinAggregateOutputType | null
  _max: EssayMaxAggregateOutputType | null
}

export type EssayMinAggregateOutputType = {
  id: string | null
  content: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type EssayMaxAggregateOutputType = {
  id: string | null
  content: string | null
  created_at: Date | null
  updated_at: Date | null
}

export type EssayCountAggregateOutputType = {
  id: number
  content: number
  images: number
  created_at: number
  updated_at: number
  _all: number
}

export type EssayMinAggregateInputType = {
  id?: true
  content?: true
  created_at?: true
  updated_at?: true
}

export type EssayMaxAggregateInputType = {
  id?: true
  content?: true
  created_at?: true
  updated_at?: true
}

export type EssayCountAggregateInputType = {
  id?: true
  content?: true
  images?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type EssayAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which essay to aggregate.
   */
  where?: Prisma.essayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of essays to fetch.
   */
  orderBy?:
    | Prisma.essayOrderByWithRelationInput
    | Prisma.essayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.essayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` essays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` essays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned essays
   **/
  _count?: true | EssayCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: EssayMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: EssayMaxAggregateInputType
}

export type GetEssayAggregateType<T extends EssayAggregateArgs> = {
  [P in keyof T & keyof AggregateEssay]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEssay[P]>
    : Prisma.GetScalarType<T[P], AggregateEssay[P]>
}

export type essayGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.essayWhereInput
  orderBy?:
    | Prisma.essayOrderByWithAggregationInput
    | Prisma.essayOrderByWithAggregationInput[]
  by: Prisma.EssayScalarFieldEnum[] | Prisma.EssayScalarFieldEnum
  having?: Prisma.essayScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EssayCountAggregateInputType | true
  _min?: EssayMinAggregateInputType
  _max?: EssayMaxAggregateInputType
}

export type EssayGroupByOutputType = {
  id: string
  content: string | null
  images: runtime.JsonValue | null
  created_at: Date
  updated_at: Date
  _count: EssayCountAggregateOutputType | null
  _min: EssayMinAggregateOutputType | null
  _max: EssayMaxAggregateOutputType | null
}

export type GetEssayGroupByPayload<T extends essayGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<EssayGroupByOutputType, T['by']> & {
        [P in keyof T & keyof EssayGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EssayGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EssayGroupByOutputType[P]>
      }
    >
  >

export type essayWhereInput = {
  AND?: Prisma.essayWhereInput | Prisma.essayWhereInput[]
  OR?: Prisma.essayWhereInput[]
  NOT?: Prisma.essayWhereInput | Prisma.essayWhereInput[]
  id?: Prisma.StringFilter<'essay'> | string
  content?: Prisma.StringNullableFilter<'essay'> | string | null
  images?: Prisma.JsonNullableFilter<'essay'>
  created_at?: Prisma.DateTimeFilter<'essay'> | Date | string
  updated_at?: Prisma.DateTimeFilter<'essay'> | Date | string
}

export type essayOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrderInput | Prisma.SortOrder
  images?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _relevance?: Prisma.essayOrderByRelevanceInput
}

export type essayWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    AND?: Prisma.essayWhereInput | Prisma.essayWhereInput[]
    OR?: Prisma.essayWhereInput[]
    NOT?: Prisma.essayWhereInput | Prisma.essayWhereInput[]
    content?: Prisma.StringNullableFilter<'essay'> | string | null
    images?: Prisma.JsonNullableFilter<'essay'>
    created_at?: Prisma.DateTimeFilter<'essay'> | Date | string
    updated_at?: Prisma.DateTimeFilter<'essay'> | Date | string
  },
  'id'
>

export type essayOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrderInput | Prisma.SortOrder
  images?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.essayCountOrderByAggregateInput
  _max?: Prisma.essayMaxOrderByAggregateInput
  _min?: Prisma.essayMinOrderByAggregateInput
}

export type essayScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.essayScalarWhereWithAggregatesInput
    | Prisma.essayScalarWhereWithAggregatesInput[]
  OR?: Prisma.essayScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.essayScalarWhereWithAggregatesInput
    | Prisma.essayScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<'essay'> | string
  content?: Prisma.StringNullableWithAggregatesFilter<'essay'> | string | null
  images?: Prisma.JsonNullableWithAggregatesFilter<'essay'>
  created_at?: Prisma.DateTimeWithAggregatesFilter<'essay'> | Date | string
  updated_at?: Prisma.DateTimeWithAggregatesFilter<'essay'> | Date | string
}

export type essayCreateInput = {
  id: string
  content?: string | null
  images?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
}

export type essayUncheckedCreateInput = {
  id: string
  content?: string | null
  images?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
}

export type essayUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type essayUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type essayCreateManyInput = {
  id: string
  content?: string | null
  images?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Date | string
  updated_at?: Date | string
}

export type essayUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type essayUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  images?: Prisma.NullableJsonNullValueInput | runtime.InputJsonValue
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type essayOrderByRelevanceInput = {
  fields:
    | Prisma.essayOrderByRelevanceFieldEnum
    | Prisma.essayOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type essayCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  images?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type essayMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type essayMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  content?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type essaySelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    content?: boolean
    images?: boolean
    created_at?: boolean
    updated_at?: boolean
  },
  ExtArgs['result']['essay']
>

export type essaySelectScalar = {
  id?: boolean
  content?: boolean
  images?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type essayOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'id' | 'content' | 'images' | 'created_at' | 'updated_at',
  ExtArgs['result']['essay']
>

export type $essayPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'essay'
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      content: string | null
      images: runtime.JsonValue | null
      created_at: Date
      updated_at: Date
    },
    ExtArgs['result']['essay']
  >
  composites: {}
}

export type essayGetPayload<
  S extends boolean | null | undefined | essayDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$essayPayload, S>

export type essayCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<essayFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: EssayCountAggregateInputType | true
}

export interface essayDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['essay']
    meta: { name: 'essay' }
  }
  /**
   * Find zero or one Essay that matches the filter.
   * @param {essayFindUniqueArgs} args - Arguments to find a Essay
   * @example
   * // Get one Essay
   * const essay = await prisma.essay.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends essayFindUniqueArgs>(
    args: Prisma.SelectSubset<T, essayFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__essayClient<
    runtime.Types.Result.GetResult<
      Prisma.$essayPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one Essay that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {essayFindUniqueOrThrowArgs} args - Arguments to find a Essay
   * @example
   * // Get one Essay
   * const essay = await prisma.essay.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends essayFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, essayFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__essayClient<
    runtime.Types.Result.GetResult<
      Prisma.$essayPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Essay that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {essayFindFirstArgs} args - Arguments to find a Essay
   * @example
   * // Get one Essay
   * const essay = await prisma.essay.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends essayFindFirstArgs>(
    args?: Prisma.SelectSubset<T, essayFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__essayClient<
    runtime.Types.Result.GetResult<
      Prisma.$essayPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Essay that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {essayFindFirstOrThrowArgs} args - Arguments to find a Essay
   * @example
   * // Get one Essay
   * const essay = await prisma.essay.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends essayFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, essayFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__essayClient<
    runtime.Types.Result.GetResult<
      Prisma.$essayPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more Essays that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {essayFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Essays
   * const essays = await prisma.essay.findMany()
   *
   * // Get first 10 Essays
   * const essays = await prisma.essay.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const essayWithIdOnly = await prisma.essay.findMany({ select: { id: true } })
   *
   */
  findMany<T extends essayFindManyArgs>(
    args?: Prisma.SelectSubset<T, essayFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$essayPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a Essay.
   * @param {essayCreateArgs} args - Arguments to create a Essay.
   * @example
   * // Create one Essay
   * const Essay = await prisma.essay.create({
   *   data: {
   *     // ... data to create a Essay
   *   }
   * })
   *
   */
  create<T extends essayCreateArgs>(
    args: Prisma.SelectSubset<T, essayCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__essayClient<
    runtime.Types.Result.GetResult<
      Prisma.$essayPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many Essays.
   * @param {essayCreateManyArgs} args - Arguments to create many Essays.
   * @example
   * // Create many Essays
   * const essay = await prisma.essay.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends essayCreateManyArgs>(
    args?: Prisma.SelectSubset<T, essayCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Essay.
   * @param {essayDeleteArgs} args - Arguments to delete one Essay.
   * @example
   * // Delete one Essay
   * const Essay = await prisma.essay.delete({
   *   where: {
   *     // ... filter to delete one Essay
   *   }
   * })
   *
   */
  delete<T extends essayDeleteArgs>(
    args: Prisma.SelectSubset<T, essayDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__essayClient<
    runtime.Types.Result.GetResult<
      Prisma.$essayPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one Essay.
   * @param {essayUpdateArgs} args - Arguments to update one Essay.
   * @example
   * // Update one Essay
   * const essay = await prisma.essay.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends essayUpdateArgs>(
    args: Prisma.SelectSubset<T, essayUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__essayClient<
    runtime.Types.Result.GetResult<
      Prisma.$essayPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more Essays.
   * @param {essayDeleteManyArgs} args - Arguments to filter Essays to delete.
   * @example
   * // Delete a few Essays
   * const { count } = await prisma.essay.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends essayDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, essayDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Essays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {essayUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Essays
   * const essay = await prisma.essay.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends essayUpdateManyArgs>(
    args: Prisma.SelectSubset<T, essayUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Essay.
   * @param {essayUpsertArgs} args - Arguments to update or create a Essay.
   * @example
   * // Update or create a Essay
   * const essay = await prisma.essay.upsert({
   *   create: {
   *     // ... data to create a Essay
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Essay we want to update
   *   }
   * })
   */
  upsert<T extends essayUpsertArgs>(
    args: Prisma.SelectSubset<T, essayUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__essayClient<
    runtime.Types.Result.GetResult<
      Prisma.$essayPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of Essays.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {essayCountArgs} args - Arguments to filter Essays to count.
   * @example
   * // Count the number of Essays
   * const count = await prisma.essay.count({
   *   where: {
   *     // ... the filter for the Essays we want to count
   *   }
   * })
   **/
  count<T extends essayCountArgs>(
    args?: Prisma.Subset<T, essayCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EssayCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Essay.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EssayAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends EssayAggregateArgs>(
    args: Prisma.Subset<T, EssayAggregateArgs>,
  ): Prisma.PrismaPromise<GetEssayAggregateType<T>>

  /**
   * Group by Essay.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {essayGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends essayGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: essayGroupByArgs['orderBy'] }
      : { orderBy?: essayGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    'Field ',
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, essayGroupByArgs, OrderByArg> &
      InputErrors,
  ): {} extends InputErrors
    ? GetEssayGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the essay model
   */
  readonly fields: essayFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for essay.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__essayClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the essay model
 */
export interface essayFieldRefs {
  readonly id: Prisma.FieldRef<'essay', 'String'>
  readonly content: Prisma.FieldRef<'essay', 'String'>
  readonly images: Prisma.FieldRef<'essay', 'Json'>
  readonly created_at: Prisma.FieldRef<'essay', 'DateTime'>
  readonly updated_at: Prisma.FieldRef<'essay', 'DateTime'>
}

// Custom InputTypes
/**
 * essay findUnique
 */
export type essayFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the essay
   */
  select?: Prisma.essaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the essay
   */
  omit?: Prisma.essayOmit<ExtArgs> | null
  /**
   * Filter, which essay to fetch.
   */
  where: Prisma.essayWhereUniqueInput
}

/**
 * essay findUniqueOrThrow
 */
export type essayFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the essay
   */
  select?: Prisma.essaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the essay
   */
  omit?: Prisma.essayOmit<ExtArgs> | null
  /**
   * Filter, which essay to fetch.
   */
  where: Prisma.essayWhereUniqueInput
}

/**
 * essay findFirst
 */
export type essayFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the essay
   */
  select?: Prisma.essaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the essay
   */
  omit?: Prisma.essayOmit<ExtArgs> | null
  /**
   * Filter, which essay to fetch.
   */
  where?: Prisma.essayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of essays to fetch.
   */
  orderBy?:
    | Prisma.essayOrderByWithRelationInput
    | Prisma.essayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for essays.
   */
  cursor?: Prisma.essayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` essays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` essays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of essays.
   */
  distinct?: Prisma.EssayScalarFieldEnum | Prisma.EssayScalarFieldEnum[]
}

/**
 * essay findFirstOrThrow
 */
export type essayFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the essay
   */
  select?: Prisma.essaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the essay
   */
  omit?: Prisma.essayOmit<ExtArgs> | null
  /**
   * Filter, which essay to fetch.
   */
  where?: Prisma.essayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of essays to fetch.
   */
  orderBy?:
    | Prisma.essayOrderByWithRelationInput
    | Prisma.essayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for essays.
   */
  cursor?: Prisma.essayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` essays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` essays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of essays.
   */
  distinct?: Prisma.EssayScalarFieldEnum | Prisma.EssayScalarFieldEnum[]
}

/**
 * essay findMany
 */
export type essayFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the essay
   */
  select?: Prisma.essaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the essay
   */
  omit?: Prisma.essayOmit<ExtArgs> | null
  /**
   * Filter, which essays to fetch.
   */
  where?: Prisma.essayWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of essays to fetch.
   */
  orderBy?:
    | Prisma.essayOrderByWithRelationInput
    | Prisma.essayOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing essays.
   */
  cursor?: Prisma.essayWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` essays from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` essays.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of essays.
   */
  distinct?: Prisma.EssayScalarFieldEnum | Prisma.EssayScalarFieldEnum[]
}

/**
 * essay create
 */
export type essayCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the essay
   */
  select?: Prisma.essaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the essay
   */
  omit?: Prisma.essayOmit<ExtArgs> | null
  /**
   * The data needed to create a essay.
   */
  data: Prisma.XOR<Prisma.essayCreateInput, Prisma.essayUncheckedCreateInput>
}

/**
 * essay createMany
 */
export type essayCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many essays.
   */
  data: Prisma.essayCreateManyInput | Prisma.essayCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * essay update
 */
export type essayUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the essay
   */
  select?: Prisma.essaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the essay
   */
  omit?: Prisma.essayOmit<ExtArgs> | null
  /**
   * The data needed to update a essay.
   */
  data: Prisma.XOR<Prisma.essayUpdateInput, Prisma.essayUncheckedUpdateInput>
  /**
   * Choose, which essay to update.
   */
  where: Prisma.essayWhereUniqueInput
}

/**
 * essay updateMany
 */
export type essayUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update essays.
   */
  data: Prisma.XOR<
    Prisma.essayUpdateManyMutationInput,
    Prisma.essayUncheckedUpdateManyInput
  >
  /**
   * Filter which essays to update
   */
  where?: Prisma.essayWhereInput
  /**
   * Limit how many essays to update.
   */
  limit?: number
}

/**
 * essay upsert
 */
export type essayUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the essay
   */
  select?: Prisma.essaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the essay
   */
  omit?: Prisma.essayOmit<ExtArgs> | null
  /**
   * The filter to search for the essay to update in case it exists.
   */
  where: Prisma.essayWhereUniqueInput
  /**
   * In case the essay found by the `where` argument doesn't exist, create a new essay with this data.
   */
  create: Prisma.XOR<Prisma.essayCreateInput, Prisma.essayUncheckedCreateInput>
  /**
   * In case the essay was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.essayUpdateInput, Prisma.essayUncheckedUpdateInput>
}

/**
 * essay delete
 */
export type essayDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the essay
   */
  select?: Prisma.essaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the essay
   */
  omit?: Prisma.essayOmit<ExtArgs> | null
  /**
   * Filter which essay to delete.
   */
  where: Prisma.essayWhereUniqueInput
}

/**
 * essay deleteMany
 */
export type essayDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which essays to delete
   */
  where?: Prisma.essayWhereInput
  /**
   * Limit how many essays to delete.
   */
  limit?: number
}

/**
 * essay without action
 */
export type essayDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the essay
   */
  select?: Prisma.essaySelect<ExtArgs> | null
  /**
   * Omit specific fields from the essay
   */
  omit?: Prisma.essayOmit<ExtArgs> | null
}
