/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `music_song` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums.js'
import type * as Prisma from '../internal/prismaNamespace.js'

/**
 * Model music_song
 *
 */
export type music_songModel =
  runtime.Types.Result.DefaultSelection<Prisma.$music_songPayload>

export type AggregateMusic_song = {
  _count: Music_songCountAggregateOutputType | null
  _avg: Music_songAvgAggregateOutputType | null
  _sum: Music_songSumAggregateOutputType | null
  _min: Music_songMinAggregateOutputType | null
  _max: Music_songMaxAggregateOutputType | null
}

export type Music_songAvgAggregateOutputType = {
  sort_order: number | null
}

export type Music_songSumAggregateOutputType = {
  sort_order: number | null
}

export type Music_songMinAggregateOutputType = {
  id: string | null
  playlist_id: string | null
  title: string | null
  artist: string | null
  album: string | null
  cover: string | null
  source_name: string | null
  source_url: string | null
  sort_order: number | null
  created_at: Date | null
}

export type Music_songMaxAggregateOutputType = {
  id: string | null
  playlist_id: string | null
  title: string | null
  artist: string | null
  album: string | null
  cover: string | null
  source_name: string | null
  source_url: string | null
  sort_order: number | null
  created_at: Date | null
}

export type Music_songCountAggregateOutputType = {
  id: number
  playlist_id: number
  title: number
  artist: number
  album: number
  cover: number
  source_name: number
  source_url: number
  sort_order: number
  created_at: number
  _all: number
}

export type Music_songAvgAggregateInputType = {
  sort_order?: true
}

export type Music_songSumAggregateInputType = {
  sort_order?: true
}

export type Music_songMinAggregateInputType = {
  id?: true
  playlist_id?: true
  title?: true
  artist?: true
  album?: true
  cover?: true
  source_name?: true
  source_url?: true
  sort_order?: true
  created_at?: true
}

export type Music_songMaxAggregateInputType = {
  id?: true
  playlist_id?: true
  title?: true
  artist?: true
  album?: true
  cover?: true
  source_name?: true
  source_url?: true
  sort_order?: true
  created_at?: true
}

export type Music_songCountAggregateInputType = {
  id?: true
  playlist_id?: true
  title?: true
  artist?: true
  album?: true
  cover?: true
  source_name?: true
  source_url?: true
  sort_order?: true
  created_at?: true
  _all?: true
}

export type Music_songAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which music_song to aggregate.
   */
  where?: Prisma.music_songWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of music_songs to fetch.
   */
  orderBy?:
    | Prisma.music_songOrderByWithRelationInput
    | Prisma.music_songOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.music_songWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` music_songs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` music_songs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned music_songs
   **/
  _count?: true | Music_songCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: Music_songAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: Music_songSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: Music_songMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: Music_songMaxAggregateInputType
}

export type GetMusic_songAggregateType<T extends Music_songAggregateArgs> = {
  [P in keyof T & keyof AggregateMusic_song]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMusic_song[P]>
    : Prisma.GetScalarType<T[P], AggregateMusic_song[P]>
}

export type music_songGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.music_songWhereInput
  orderBy?:
    | Prisma.music_songOrderByWithAggregationInput
    | Prisma.music_songOrderByWithAggregationInput[]
  by: Prisma.Music_songScalarFieldEnum[] | Prisma.Music_songScalarFieldEnum
  having?: Prisma.music_songScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Music_songCountAggregateInputType | true
  _avg?: Music_songAvgAggregateInputType
  _sum?: Music_songSumAggregateInputType
  _min?: Music_songMinAggregateInputType
  _max?: Music_songMaxAggregateInputType
}

export type Music_songGroupByOutputType = {
  id: string
  playlist_id: string
  title: string
  artist: string | null
  album: string | null
  cover: string | null
  source_name: string | null
  source_url: string | null
  sort_order: number
  created_at: Date
  _count: Music_songCountAggregateOutputType | null
  _avg: Music_songAvgAggregateOutputType | null
  _sum: Music_songSumAggregateOutputType | null
  _min: Music_songMinAggregateOutputType | null
  _max: Music_songMaxAggregateOutputType | null
}

export type GetMusic_songGroupByPayload<T extends music_songGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<Music_songGroupByOutputType, T['by']> & {
        [P in keyof T & keyof Music_songGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Music_songGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Music_songGroupByOutputType[P]>
      }
    >
  >

export type music_songWhereInput = {
  AND?: Prisma.music_songWhereInput | Prisma.music_songWhereInput[]
  OR?: Prisma.music_songWhereInput[]
  NOT?: Prisma.music_songWhereInput | Prisma.music_songWhereInput[]
  id?: Prisma.StringFilter<'music_song'> | string
  playlist_id?: Prisma.StringFilter<'music_song'> | string
  title?: Prisma.StringFilter<'music_song'> | string
  artist?: Prisma.StringNullableFilter<'music_song'> | string | null
  album?: Prisma.StringNullableFilter<'music_song'> | string | null
  cover?: Prisma.StringNullableFilter<'music_song'> | string | null
  source_name?: Prisma.StringNullableFilter<'music_song'> | string | null
  source_url?: Prisma.StringNullableFilter<'music_song'> | string | null
  sort_order?: Prisma.IntFilter<'music_song'> | number
  created_at?: Prisma.DateTimeFilter<'music_song'> | Date | string
  playlist?: Prisma.XOR<
    Prisma.Music_playlistScalarRelationFilter,
    Prisma.music_playlistWhereInput
  >
}

export type music_songOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  playlist_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  artist?: Prisma.SortOrderInput | Prisma.SortOrder
  album?: Prisma.SortOrderInput | Prisma.SortOrder
  cover?: Prisma.SortOrderInput | Prisma.SortOrder
  source_name?: Prisma.SortOrderInput | Prisma.SortOrder
  source_url?: Prisma.SortOrderInput | Prisma.SortOrder
  sort_order?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  playlist?: Prisma.music_playlistOrderByWithRelationInput
  _relevance?: Prisma.music_songOrderByRelevanceInput
}

export type music_songWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    AND?: Prisma.music_songWhereInput | Prisma.music_songWhereInput[]
    OR?: Prisma.music_songWhereInput[]
    NOT?: Prisma.music_songWhereInput | Prisma.music_songWhereInput[]
    playlist_id?: Prisma.StringFilter<'music_song'> | string
    title?: Prisma.StringFilter<'music_song'> | string
    artist?: Prisma.StringNullableFilter<'music_song'> | string | null
    album?: Prisma.StringNullableFilter<'music_song'> | string | null
    cover?: Prisma.StringNullableFilter<'music_song'> | string | null
    source_name?: Prisma.StringNullableFilter<'music_song'> | string | null
    source_url?: Prisma.StringNullableFilter<'music_song'> | string | null
    sort_order?: Prisma.IntFilter<'music_song'> | number
    created_at?: Prisma.DateTimeFilter<'music_song'> | Date | string
    playlist?: Prisma.XOR<
      Prisma.Music_playlistScalarRelationFilter,
      Prisma.music_playlistWhereInput
    >
  },
  'id'
>

export type music_songOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  playlist_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  artist?: Prisma.SortOrderInput | Prisma.SortOrder
  album?: Prisma.SortOrderInput | Prisma.SortOrder
  cover?: Prisma.SortOrderInput | Prisma.SortOrder
  source_name?: Prisma.SortOrderInput | Prisma.SortOrder
  source_url?: Prisma.SortOrderInput | Prisma.SortOrder
  sort_order?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  _count?: Prisma.music_songCountOrderByAggregateInput
  _avg?: Prisma.music_songAvgOrderByAggregateInput
  _max?: Prisma.music_songMaxOrderByAggregateInput
  _min?: Prisma.music_songMinOrderByAggregateInput
  _sum?: Prisma.music_songSumOrderByAggregateInput
}

export type music_songScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.music_songScalarWhereWithAggregatesInput
    | Prisma.music_songScalarWhereWithAggregatesInput[]
  OR?: Prisma.music_songScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.music_songScalarWhereWithAggregatesInput
    | Prisma.music_songScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<'music_song'> | string
  playlist_id?: Prisma.StringWithAggregatesFilter<'music_song'> | string
  title?: Prisma.StringWithAggregatesFilter<'music_song'> | string
  artist?:
    | Prisma.StringNullableWithAggregatesFilter<'music_song'>
    | string
    | null
  album?:
    | Prisma.StringNullableWithAggregatesFilter<'music_song'>
    | string
    | null
  cover?:
    | Prisma.StringNullableWithAggregatesFilter<'music_song'>
    | string
    | null
  source_name?:
    | Prisma.StringNullableWithAggregatesFilter<'music_song'>
    | string
    | null
  source_url?:
    | Prisma.StringNullableWithAggregatesFilter<'music_song'>
    | string
    | null
  sort_order?: Prisma.IntWithAggregatesFilter<'music_song'> | number
  created_at?: Prisma.DateTimeWithAggregatesFilter<'music_song'> | Date | string
}

export type music_songCreateInput = {
  id: string
  title: string
  artist?: string | null
  album?: string | null
  cover?: string | null
  source_name?: string | null
  source_url?: string | null
  sort_order?: number
  created_at?: Date | string
  playlist: Prisma.music_playlistCreateNestedOneWithoutSongsInput
}

export type music_songUncheckedCreateInput = {
  id: string
  playlist_id: string
  title: string
  artist?: string | null
  album?: string | null
  cover?: string | null
  source_name?: string | null
  source_url?: string | null
  sort_order?: number
  created_at?: Date | string
}

export type music_songUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  artist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  album?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cover?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sort_order?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  playlist?: Prisma.music_playlistUpdateOneRequiredWithoutSongsNestedInput
}

export type music_songUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playlist_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  artist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  album?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cover?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sort_order?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type music_songCreateManyInput = {
  id: string
  playlist_id: string
  title: string
  artist?: string | null
  album?: string | null
  cover?: string | null
  source_name?: string | null
  source_url?: string | null
  sort_order?: number
  created_at?: Date | string
}

export type music_songUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  artist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  album?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cover?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sort_order?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type music_songUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  playlist_id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  artist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  album?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cover?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sort_order?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type Music_songListRelationFilter = {
  every?: Prisma.music_songWhereInput
  some?: Prisma.music_songWhereInput
  none?: Prisma.music_songWhereInput
}

export type music_songOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type music_songOrderByRelevanceInput = {
  fields:
    | Prisma.music_songOrderByRelevanceFieldEnum
    | Prisma.music_songOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type music_songCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playlist_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  artist?: Prisma.SortOrder
  album?: Prisma.SortOrder
  cover?: Prisma.SortOrder
  source_name?: Prisma.SortOrder
  source_url?: Prisma.SortOrder
  sort_order?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type music_songAvgOrderByAggregateInput = {
  sort_order?: Prisma.SortOrder
}

export type music_songMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playlist_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  artist?: Prisma.SortOrder
  album?: Prisma.SortOrder
  cover?: Prisma.SortOrder
  source_name?: Prisma.SortOrder
  source_url?: Prisma.SortOrder
  sort_order?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type music_songMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  playlist_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  artist?: Prisma.SortOrder
  album?: Prisma.SortOrder
  cover?: Prisma.SortOrder
  source_name?: Prisma.SortOrder
  source_url?: Prisma.SortOrder
  sort_order?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type music_songSumOrderByAggregateInput = {
  sort_order?: Prisma.SortOrder
}

export type music_songCreateNestedManyWithoutPlaylistInput = {
  create?:
    | Prisma.XOR<
        Prisma.music_songCreateWithoutPlaylistInput,
        Prisma.music_songUncheckedCreateWithoutPlaylistInput
      >
    | Prisma.music_songCreateWithoutPlaylistInput[]
    | Prisma.music_songUncheckedCreateWithoutPlaylistInput[]
  connectOrCreate?:
    | Prisma.music_songCreateOrConnectWithoutPlaylistInput
    | Prisma.music_songCreateOrConnectWithoutPlaylistInput[]
  createMany?: Prisma.music_songCreateManyPlaylistInputEnvelope
  connect?:
    | Prisma.music_songWhereUniqueInput
    | Prisma.music_songWhereUniqueInput[]
}

export type music_songUncheckedCreateNestedManyWithoutPlaylistInput = {
  create?:
    | Prisma.XOR<
        Prisma.music_songCreateWithoutPlaylistInput,
        Prisma.music_songUncheckedCreateWithoutPlaylistInput
      >
    | Prisma.music_songCreateWithoutPlaylistInput[]
    | Prisma.music_songUncheckedCreateWithoutPlaylistInput[]
  connectOrCreate?:
    | Prisma.music_songCreateOrConnectWithoutPlaylistInput
    | Prisma.music_songCreateOrConnectWithoutPlaylistInput[]
  createMany?: Prisma.music_songCreateManyPlaylistInputEnvelope
  connect?:
    | Prisma.music_songWhereUniqueInput
    | Prisma.music_songWhereUniqueInput[]
}

export type music_songUpdateManyWithoutPlaylistNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.music_songCreateWithoutPlaylistInput,
        Prisma.music_songUncheckedCreateWithoutPlaylistInput
      >
    | Prisma.music_songCreateWithoutPlaylistInput[]
    | Prisma.music_songUncheckedCreateWithoutPlaylistInput[]
  connectOrCreate?:
    | Prisma.music_songCreateOrConnectWithoutPlaylistInput
    | Prisma.music_songCreateOrConnectWithoutPlaylistInput[]
  upsert?:
    | Prisma.music_songUpsertWithWhereUniqueWithoutPlaylistInput
    | Prisma.music_songUpsertWithWhereUniqueWithoutPlaylistInput[]
  createMany?: Prisma.music_songCreateManyPlaylistInputEnvelope
  set?: Prisma.music_songWhereUniqueInput | Prisma.music_songWhereUniqueInput[]
  disconnect?:
    | Prisma.music_songWhereUniqueInput
    | Prisma.music_songWhereUniqueInput[]
  delete?:
    | Prisma.music_songWhereUniqueInput
    | Prisma.music_songWhereUniqueInput[]
  connect?:
    | Prisma.music_songWhereUniqueInput
    | Prisma.music_songWhereUniqueInput[]
  update?:
    | Prisma.music_songUpdateWithWhereUniqueWithoutPlaylistInput
    | Prisma.music_songUpdateWithWhereUniqueWithoutPlaylistInput[]
  updateMany?:
    | Prisma.music_songUpdateManyWithWhereWithoutPlaylistInput
    | Prisma.music_songUpdateManyWithWhereWithoutPlaylistInput[]
  deleteMany?:
    | Prisma.music_songScalarWhereInput
    | Prisma.music_songScalarWhereInput[]
}

export type music_songUncheckedUpdateManyWithoutPlaylistNestedInput = {
  create?:
    | Prisma.XOR<
        Prisma.music_songCreateWithoutPlaylistInput,
        Prisma.music_songUncheckedCreateWithoutPlaylistInput
      >
    | Prisma.music_songCreateWithoutPlaylistInput[]
    | Prisma.music_songUncheckedCreateWithoutPlaylistInput[]
  connectOrCreate?:
    | Prisma.music_songCreateOrConnectWithoutPlaylistInput
    | Prisma.music_songCreateOrConnectWithoutPlaylistInput[]
  upsert?:
    | Prisma.music_songUpsertWithWhereUniqueWithoutPlaylistInput
    | Prisma.music_songUpsertWithWhereUniqueWithoutPlaylistInput[]
  createMany?: Prisma.music_songCreateManyPlaylistInputEnvelope
  set?: Prisma.music_songWhereUniqueInput | Prisma.music_songWhereUniqueInput[]
  disconnect?:
    | Prisma.music_songWhereUniqueInput
    | Prisma.music_songWhereUniqueInput[]
  delete?:
    | Prisma.music_songWhereUniqueInput
    | Prisma.music_songWhereUniqueInput[]
  connect?:
    | Prisma.music_songWhereUniqueInput
    | Prisma.music_songWhereUniqueInput[]
  update?:
    | Prisma.music_songUpdateWithWhereUniqueWithoutPlaylistInput
    | Prisma.music_songUpdateWithWhereUniqueWithoutPlaylistInput[]
  updateMany?:
    | Prisma.music_songUpdateManyWithWhereWithoutPlaylistInput
    | Prisma.music_songUpdateManyWithWhereWithoutPlaylistInput[]
  deleteMany?:
    | Prisma.music_songScalarWhereInput
    | Prisma.music_songScalarWhereInput[]
}

export type music_songCreateWithoutPlaylistInput = {
  id: string
  title: string
  artist?: string | null
  album?: string | null
  cover?: string | null
  source_name?: string | null
  source_url?: string | null
  sort_order?: number
  created_at?: Date | string
}

export type music_songUncheckedCreateWithoutPlaylistInput = {
  id: string
  title: string
  artist?: string | null
  album?: string | null
  cover?: string | null
  source_name?: string | null
  source_url?: string | null
  sort_order?: number
  created_at?: Date | string
}

export type music_songCreateOrConnectWithoutPlaylistInput = {
  where: Prisma.music_songWhereUniqueInput
  create: Prisma.XOR<
    Prisma.music_songCreateWithoutPlaylistInput,
    Prisma.music_songUncheckedCreateWithoutPlaylistInput
  >
}

export type music_songCreateManyPlaylistInputEnvelope = {
  data:
    | Prisma.music_songCreateManyPlaylistInput
    | Prisma.music_songCreateManyPlaylistInput[]
  skipDuplicates?: boolean
}

export type music_songUpsertWithWhereUniqueWithoutPlaylistInput = {
  where: Prisma.music_songWhereUniqueInput
  update: Prisma.XOR<
    Prisma.music_songUpdateWithoutPlaylistInput,
    Prisma.music_songUncheckedUpdateWithoutPlaylistInput
  >
  create: Prisma.XOR<
    Prisma.music_songCreateWithoutPlaylistInput,
    Prisma.music_songUncheckedCreateWithoutPlaylistInput
  >
}

export type music_songUpdateWithWhereUniqueWithoutPlaylistInput = {
  where: Prisma.music_songWhereUniqueInput
  data: Prisma.XOR<
    Prisma.music_songUpdateWithoutPlaylistInput,
    Prisma.music_songUncheckedUpdateWithoutPlaylistInput
  >
}

export type music_songUpdateManyWithWhereWithoutPlaylistInput = {
  where: Prisma.music_songScalarWhereInput
  data: Prisma.XOR<
    Prisma.music_songUpdateManyMutationInput,
    Prisma.music_songUncheckedUpdateManyWithoutPlaylistInput
  >
}

export type music_songScalarWhereInput = {
  AND?: Prisma.music_songScalarWhereInput | Prisma.music_songScalarWhereInput[]
  OR?: Prisma.music_songScalarWhereInput[]
  NOT?: Prisma.music_songScalarWhereInput | Prisma.music_songScalarWhereInput[]
  id?: Prisma.StringFilter<'music_song'> | string
  playlist_id?: Prisma.StringFilter<'music_song'> | string
  title?: Prisma.StringFilter<'music_song'> | string
  artist?: Prisma.StringNullableFilter<'music_song'> | string | null
  album?: Prisma.StringNullableFilter<'music_song'> | string | null
  cover?: Prisma.StringNullableFilter<'music_song'> | string | null
  source_name?: Prisma.StringNullableFilter<'music_song'> | string | null
  source_url?: Prisma.StringNullableFilter<'music_song'> | string | null
  sort_order?: Prisma.IntFilter<'music_song'> | number
  created_at?: Prisma.DateTimeFilter<'music_song'> | Date | string
}

export type music_songCreateManyPlaylistInput = {
  id: string
  title: string
  artist?: string | null
  album?: string | null
  cover?: string | null
  source_name?: string | null
  source_url?: string | null
  sort_order?: number
  created_at?: Date | string
}

export type music_songUpdateWithoutPlaylistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  artist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  album?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cover?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sort_order?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type music_songUncheckedUpdateWithoutPlaylistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  artist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  album?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cover?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sort_order?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type music_songUncheckedUpdateManyWithoutPlaylistInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  artist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  album?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cover?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sort_order?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type music_songSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    playlist_id?: boolean
    title?: boolean
    artist?: boolean
    album?: boolean
    cover?: boolean
    source_name?: boolean
    source_url?: boolean
    sort_order?: boolean
    created_at?: boolean
    playlist?: boolean | Prisma.music_playlistDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['music_song']
>

export type music_songSelectScalar = {
  id?: boolean
  playlist_id?: boolean
  title?: boolean
  artist?: boolean
  album?: boolean
  cover?: boolean
  source_name?: boolean
  source_url?: boolean
  sort_order?: boolean
  created_at?: boolean
}

export type music_songOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'playlist_id'
  | 'title'
  | 'artist'
  | 'album'
  | 'cover'
  | 'source_name'
  | 'source_url'
  | 'sort_order'
  | 'created_at',
  ExtArgs['result']['music_song']
>
export type music_songInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  playlist?: boolean | Prisma.music_playlistDefaultArgs<ExtArgs>
}

export type $music_songPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'music_song'
  objects: {
    playlist: Prisma.$music_playlistPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      playlist_id: string
      title: string
      artist: string | null
      album: string | null
      cover: string | null
      source_name: string | null
      source_url: string | null
      sort_order: number
      created_at: Date
    },
    ExtArgs['result']['music_song']
  >
  composites: {}
}

export type music_songGetPayload<
  S extends boolean | null | undefined | music_songDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$music_songPayload, S>

export type music_songCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<music_songFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: Music_songCountAggregateInputType | true
}

export interface music_songDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['music_song']
    meta: { name: 'music_song' }
  }
  /**
   * Find zero or one Music_song that matches the filter.
   * @param {music_songFindUniqueArgs} args - Arguments to find a Music_song
   * @example
   * // Get one Music_song
   * const music_song = await prisma.music_song.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends music_songFindUniqueArgs>(
    args: Prisma.SelectSubset<T, music_songFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__music_songClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_songPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one Music_song that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {music_songFindUniqueOrThrowArgs} args - Arguments to find a Music_song
   * @example
   * // Get one Music_song
   * const music_song = await prisma.music_song.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends music_songFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, music_songFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__music_songClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_songPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Music_song that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {music_songFindFirstArgs} args - Arguments to find a Music_song
   * @example
   * // Get one Music_song
   * const music_song = await prisma.music_song.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends music_songFindFirstArgs>(
    args?: Prisma.SelectSubset<T, music_songFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__music_songClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_songPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Music_song that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {music_songFindFirstOrThrowArgs} args - Arguments to find a Music_song
   * @example
   * // Get one Music_song
   * const music_song = await prisma.music_song.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends music_songFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, music_songFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__music_songClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_songPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more Music_songs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {music_songFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Music_songs
   * const music_songs = await prisma.music_song.findMany()
   *
   * // Get first 10 Music_songs
   * const music_songs = await prisma.music_song.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const music_songWithIdOnly = await prisma.music_song.findMany({ select: { id: true } })
   *
   */
  findMany<T extends music_songFindManyArgs>(
    args?: Prisma.SelectSubset<T, music_songFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$music_songPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a Music_song.
   * @param {music_songCreateArgs} args - Arguments to create a Music_song.
   * @example
   * // Create one Music_song
   * const Music_song = await prisma.music_song.create({
   *   data: {
   *     // ... data to create a Music_song
   *   }
   * })
   *
   */
  create<T extends music_songCreateArgs>(
    args: Prisma.SelectSubset<T, music_songCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__music_songClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_songPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many Music_songs.
   * @param {music_songCreateManyArgs} args - Arguments to create many Music_songs.
   * @example
   * // Create many Music_songs
   * const music_song = await prisma.music_song.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends music_songCreateManyArgs>(
    args?: Prisma.SelectSubset<T, music_songCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Music_song.
   * @param {music_songDeleteArgs} args - Arguments to delete one Music_song.
   * @example
   * // Delete one Music_song
   * const Music_song = await prisma.music_song.delete({
   *   where: {
   *     // ... filter to delete one Music_song
   *   }
   * })
   *
   */
  delete<T extends music_songDeleteArgs>(
    args: Prisma.SelectSubset<T, music_songDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__music_songClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_songPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one Music_song.
   * @param {music_songUpdateArgs} args - Arguments to update one Music_song.
   * @example
   * // Update one Music_song
   * const music_song = await prisma.music_song.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends music_songUpdateArgs>(
    args: Prisma.SelectSubset<T, music_songUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__music_songClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_songPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more Music_songs.
   * @param {music_songDeleteManyArgs} args - Arguments to filter Music_songs to delete.
   * @example
   * // Delete a few Music_songs
   * const { count } = await prisma.music_song.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends music_songDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, music_songDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Music_songs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {music_songUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Music_songs
   * const music_song = await prisma.music_song.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends music_songUpdateManyArgs>(
    args: Prisma.SelectSubset<T, music_songUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Music_song.
   * @param {music_songUpsertArgs} args - Arguments to update or create a Music_song.
   * @example
   * // Update or create a Music_song
   * const music_song = await prisma.music_song.upsert({
   *   create: {
   *     // ... data to create a Music_song
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Music_song we want to update
   *   }
   * })
   */
  upsert<T extends music_songUpsertArgs>(
    args: Prisma.SelectSubset<T, music_songUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__music_songClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_songPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of Music_songs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {music_songCountArgs} args - Arguments to filter Music_songs to count.
   * @example
   * // Count the number of Music_songs
   * const count = await prisma.music_song.count({
   *   where: {
   *     // ... the filter for the Music_songs we want to count
   *   }
   * })
   **/
  count<T extends music_songCountArgs>(
    args?: Prisma.Subset<T, music_songCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Music_songCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Music_song.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Music_songAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends Music_songAggregateArgs>(
    args: Prisma.Subset<T, Music_songAggregateArgs>,
  ): Prisma.PrismaPromise<GetMusic_songAggregateType<T>>

  /**
   * Group by Music_song.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {music_songGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends music_songGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends (Prisma.True extends HasSelectOrTake
      ? { orderBy: music_songGroupByArgs['orderBy'] }
      : { orderBy?: music_songGroupByArgs['orderBy'] }),
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends (T['by'] extends never[] ? Prisma.True : Prisma.False),
    InputErrors extends (ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    'Field ',
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]),
  >(
    args: Prisma.SubsetIntersection<T, music_songGroupByArgs, OrderByArg> &
      InputErrors,
  ): {} extends InputErrors
    ? GetMusic_songGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the music_song model
   */
  readonly fields: music_songFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for music_song.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__music_songClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  playlist<T extends Prisma.music_playlistDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.music_playlistDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__music_playlistClient<
    | runtime.Types.Result.GetResult<
        Prisma.$music_playlistPayload<ExtArgs>,
        T,
        'findUniqueOrThrow',
        GlobalOmitOptions
      >
    | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the music_song model
 */
export interface music_songFieldRefs {
  readonly id: Prisma.FieldRef<'music_song', 'String'>
  readonly playlist_id: Prisma.FieldRef<'music_song', 'String'>
  readonly title: Prisma.FieldRef<'music_song', 'String'>
  readonly artist: Prisma.FieldRef<'music_song', 'String'>
  readonly album: Prisma.FieldRef<'music_song', 'String'>
  readonly cover: Prisma.FieldRef<'music_song', 'String'>
  readonly source_name: Prisma.FieldRef<'music_song', 'String'>
  readonly source_url: Prisma.FieldRef<'music_song', 'String'>
  readonly sort_order: Prisma.FieldRef<'music_song', 'Int'>
  readonly created_at: Prisma.FieldRef<'music_song', 'DateTime'>
}

// Custom InputTypes
/**
 * music_song findUnique
 */
export type music_songFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_song
   */
  select?: Prisma.music_songSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_song
   */
  omit?: Prisma.music_songOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_songInclude<ExtArgs> | null
  /**
   * Filter, which music_song to fetch.
   */
  where: Prisma.music_songWhereUniqueInput
}

/**
 * music_song findUniqueOrThrow
 */
export type music_songFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_song
   */
  select?: Prisma.music_songSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_song
   */
  omit?: Prisma.music_songOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_songInclude<ExtArgs> | null
  /**
   * Filter, which music_song to fetch.
   */
  where: Prisma.music_songWhereUniqueInput
}

/**
 * music_song findFirst
 */
export type music_songFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_song
   */
  select?: Prisma.music_songSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_song
   */
  omit?: Prisma.music_songOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_songInclude<ExtArgs> | null
  /**
   * Filter, which music_song to fetch.
   */
  where?: Prisma.music_songWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of music_songs to fetch.
   */
  orderBy?:
    | Prisma.music_songOrderByWithRelationInput
    | Prisma.music_songOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for music_songs.
   */
  cursor?: Prisma.music_songWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` music_songs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` music_songs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of music_songs.
   */
  distinct?:
    | Prisma.Music_songScalarFieldEnum
    | Prisma.Music_songScalarFieldEnum[]
}

/**
 * music_song findFirstOrThrow
 */
export type music_songFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_song
   */
  select?: Prisma.music_songSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_song
   */
  omit?: Prisma.music_songOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_songInclude<ExtArgs> | null
  /**
   * Filter, which music_song to fetch.
   */
  where?: Prisma.music_songWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of music_songs to fetch.
   */
  orderBy?:
    | Prisma.music_songOrderByWithRelationInput
    | Prisma.music_songOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for music_songs.
   */
  cursor?: Prisma.music_songWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` music_songs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` music_songs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of music_songs.
   */
  distinct?:
    | Prisma.Music_songScalarFieldEnum
    | Prisma.Music_songScalarFieldEnum[]
}

/**
 * music_song findMany
 */
export type music_songFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_song
   */
  select?: Prisma.music_songSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_song
   */
  omit?: Prisma.music_songOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_songInclude<ExtArgs> | null
  /**
   * Filter, which music_songs to fetch.
   */
  where?: Prisma.music_songWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of music_songs to fetch.
   */
  orderBy?:
    | Prisma.music_songOrderByWithRelationInput
    | Prisma.music_songOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing music_songs.
   */
  cursor?: Prisma.music_songWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` music_songs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` music_songs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of music_songs.
   */
  distinct?:
    | Prisma.Music_songScalarFieldEnum
    | Prisma.Music_songScalarFieldEnum[]
}

/**
 * music_song create
 */
export type music_songCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_song
   */
  select?: Prisma.music_songSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_song
   */
  omit?: Prisma.music_songOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_songInclude<ExtArgs> | null
  /**
   * The data needed to create a music_song.
   */
  data: Prisma.XOR<
    Prisma.music_songCreateInput,
    Prisma.music_songUncheckedCreateInput
  >
}

/**
 * music_song createMany
 */
export type music_songCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many music_songs.
   */
  data: Prisma.music_songCreateManyInput | Prisma.music_songCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * music_song update
 */
export type music_songUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_song
   */
  select?: Prisma.music_songSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_song
   */
  omit?: Prisma.music_songOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_songInclude<ExtArgs> | null
  /**
   * The data needed to update a music_song.
   */
  data: Prisma.XOR<
    Prisma.music_songUpdateInput,
    Prisma.music_songUncheckedUpdateInput
  >
  /**
   * Choose, which music_song to update.
   */
  where: Prisma.music_songWhereUniqueInput
}

/**
 * music_song updateMany
 */
export type music_songUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update music_songs.
   */
  data: Prisma.XOR<
    Prisma.music_songUpdateManyMutationInput,
    Prisma.music_songUncheckedUpdateManyInput
  >
  /**
   * Filter which music_songs to update
   */
  where?: Prisma.music_songWhereInput
  /**
   * Limit how many music_songs to update.
   */
  limit?: number
}

/**
 * music_song upsert
 */
export type music_songUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_song
   */
  select?: Prisma.music_songSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_song
   */
  omit?: Prisma.music_songOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_songInclude<ExtArgs> | null
  /**
   * The filter to search for the music_song to update in case it exists.
   */
  where: Prisma.music_songWhereUniqueInput
  /**
   * In case the music_song found by the `where` argument doesn't exist, create a new music_song with this data.
   */
  create: Prisma.XOR<
    Prisma.music_songCreateInput,
    Prisma.music_songUncheckedCreateInput
  >
  /**
   * In case the music_song was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.music_songUpdateInput,
    Prisma.music_songUncheckedUpdateInput
  >
}

/**
 * music_song delete
 */
export type music_songDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_song
   */
  select?: Prisma.music_songSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_song
   */
  omit?: Prisma.music_songOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_songInclude<ExtArgs> | null
  /**
   * Filter which music_song to delete.
   */
  where: Prisma.music_songWhereUniqueInput
}

/**
 * music_song deleteMany
 */
export type music_songDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which music_songs to delete
   */
  where?: Prisma.music_songWhereInput
  /**
   * Limit how many music_songs to delete.
   */
  limit?: number
}

/**
 * music_song without action
 */
export type music_songDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_song
   */
  select?: Prisma.music_songSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_song
   */
  omit?: Prisma.music_songOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_songInclude<ExtArgs> | null
}
