/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `music_playlist` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums.js'
import type * as Prisma from '../internal/prismaNamespace.js'

/**
 * Model music_playlist
 *
 */
export type music_playlistModel =
  runtime.Types.Result.DefaultSelection<Prisma.$music_playlistPayload>

export type AggregateMusic_playlist = {
  _count: Music_playlistCountAggregateOutputType | null
  _avg: Music_playlistAvgAggregateOutputType | null
  _sum: Music_playlistSumAggregateOutputType | null
  _min: Music_playlistMinAggregateOutputType | null
  _max: Music_playlistMaxAggregateOutputType | null
}

export type Music_playlistAvgAggregateOutputType = {
  sort_order: number | null
}

export type Music_playlistSumAggregateOutputType = {
  sort_order: number | null
}

export type Music_playlistMinAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  cover: string | null
  sort_order: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type Music_playlistMaxAggregateOutputType = {
  id: string | null
  title: string | null
  description: string | null
  cover: string | null
  sort_order: number | null
  created_at: Date | null
  updated_at: Date | null
}

export type Music_playlistCountAggregateOutputType = {
  id: number
  title: number
  description: number
  cover: number
  sort_order: number
  created_at: number
  updated_at: number
  _all: number
}

export type Music_playlistAvgAggregateInputType = {
  sort_order?: true
}

export type Music_playlistSumAggregateInputType = {
  sort_order?: true
}

export type Music_playlistMinAggregateInputType = {
  id?: true
  title?: true
  description?: true
  cover?: true
  sort_order?: true
  created_at?: true
  updated_at?: true
}

export type Music_playlistMaxAggregateInputType = {
  id?: true
  title?: true
  description?: true
  cover?: true
  sort_order?: true
  created_at?: true
  updated_at?: true
}

export type Music_playlistCountAggregateInputType = {
  id?: true
  title?: true
  description?: true
  cover?: true
  sort_order?: true
  created_at?: true
  updated_at?: true
  _all?: true
}

export type Music_playlistAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which music_playlist to aggregate.
   */
  where?: Prisma.music_playlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of music_playlists to fetch.
   */
  orderBy?:
    | Prisma.music_playlistOrderByWithRelationInput
    | Prisma.music_playlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.music_playlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` music_playlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` music_playlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned music_playlists
   **/
  _count?: true | Music_playlistCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: Music_playlistAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: Music_playlistSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: Music_playlistMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: Music_playlistMaxAggregateInputType
}

export type GetMusic_playlistAggregateType<
  T extends Music_playlistAggregateArgs,
> = {
  [P in keyof T & keyof AggregateMusic_playlist]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMusic_playlist[P]>
    : Prisma.GetScalarType<T[P], AggregateMusic_playlist[P]>
}

export type music_playlistGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.music_playlistWhereInput
  orderBy?:
    | Prisma.music_playlistOrderByWithAggregationInput
    | Prisma.music_playlistOrderByWithAggregationInput[]
  by:
    | Prisma.Music_playlistScalarFieldEnum[]
    | Prisma.Music_playlistScalarFieldEnum
  having?: Prisma.music_playlistScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Music_playlistCountAggregateInputType | true
  _avg?: Music_playlistAvgAggregateInputType
  _sum?: Music_playlistSumAggregateInputType
  _min?: Music_playlistMinAggregateInputType
  _max?: Music_playlistMaxAggregateInputType
}

export type Music_playlistGroupByOutputType = {
  id: string
  title: string
  description: string | null
  cover: string | null
  sort_order: number
  created_at: Date
  updated_at: Date
  _count: Music_playlistCountAggregateOutputType | null
  _avg: Music_playlistAvgAggregateOutputType | null
  _sum: Music_playlistSumAggregateOutputType | null
  _min: Music_playlistMinAggregateOutputType | null
  _max: Music_playlistMaxAggregateOutputType | null
}

export type GetMusic_playlistGroupByPayload<
  T extends music_playlistGroupByArgs,
> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Music_playlistGroupByOutputType, T['by']> & {
      [P in keyof T & keyof Music_playlistGroupByOutputType]: P extends '_count'
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], Music_playlistGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], Music_playlistGroupByOutputType[P]>
    }
  >
>

export type music_playlistWhereInput = {
  AND?: Prisma.music_playlistWhereInput | Prisma.music_playlistWhereInput[]
  OR?: Prisma.music_playlistWhereInput[]
  NOT?: Prisma.music_playlistWhereInput | Prisma.music_playlistWhereInput[]
  id?: Prisma.StringFilter<'music_playlist'> | string
  title?: Prisma.StringFilter<'music_playlist'> | string
  description?: Prisma.StringNullableFilter<'music_playlist'> | string | null
  cover?: Prisma.StringNullableFilter<'music_playlist'> | string | null
  sort_order?: Prisma.IntFilter<'music_playlist'> | number
  created_at?: Prisma.DateTimeFilter<'music_playlist'> | Date | string
  updated_at?: Prisma.DateTimeFilter<'music_playlist'> | Date | string
  songs?: Prisma.Music_songListRelationFilter
}

export type music_playlistOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  cover?: Prisma.SortOrderInput | Prisma.SortOrder
  sort_order?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  songs?: Prisma.music_songOrderByRelationAggregateInput
  _relevance?: Prisma.music_playlistOrderByRelevanceInput
}

export type music_playlistWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    AND?: Prisma.music_playlistWhereInput | Prisma.music_playlistWhereInput[]
    OR?: Prisma.music_playlistWhereInput[]
    NOT?: Prisma.music_playlistWhereInput | Prisma.music_playlistWhereInput[]
    title?: Prisma.StringFilter<'music_playlist'> | string
    description?: Prisma.StringNullableFilter<'music_playlist'> | string | null
    cover?: Prisma.StringNullableFilter<'music_playlist'> | string | null
    sort_order?: Prisma.IntFilter<'music_playlist'> | number
    created_at?: Prisma.DateTimeFilter<'music_playlist'> | Date | string
    updated_at?: Prisma.DateTimeFilter<'music_playlist'> | Date | string
    songs?: Prisma.Music_songListRelationFilter
  },
  'id'
>

export type music_playlistOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  cover?: Prisma.SortOrderInput | Prisma.SortOrder
  sort_order?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  _count?: Prisma.music_playlistCountOrderByAggregateInput
  _avg?: Prisma.music_playlistAvgOrderByAggregateInput
  _max?: Prisma.music_playlistMaxOrderByAggregateInput
  _min?: Prisma.music_playlistMinOrderByAggregateInput
  _sum?: Prisma.music_playlistSumOrderByAggregateInput
}

export type music_playlistScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.music_playlistScalarWhereWithAggregatesInput
    | Prisma.music_playlistScalarWhereWithAggregatesInput[]
  OR?: Prisma.music_playlistScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.music_playlistScalarWhereWithAggregatesInput
    | Prisma.music_playlistScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<'music_playlist'> | string
  title?: Prisma.StringWithAggregatesFilter<'music_playlist'> | string
  description?:
    | Prisma.StringNullableWithAggregatesFilter<'music_playlist'>
    | string
    | null
  cover?:
    | Prisma.StringNullableWithAggregatesFilter<'music_playlist'>
    | string
    | null
  sort_order?: Prisma.IntWithAggregatesFilter<'music_playlist'> | number
  created_at?:
    | Prisma.DateTimeWithAggregatesFilter<'music_playlist'>
    | Date
    | string
  updated_at?:
    | Prisma.DateTimeWithAggregatesFilter<'music_playlist'>
    | Date
    | string
}

export type music_playlistCreateInput = {
  id: string
  title: string
  description?: string | null
  cover?: string | null
  sort_order?: number
  created_at?: Date | string
  updated_at?: Date | string
  songs?: Prisma.music_songCreateNestedManyWithoutPlaylistInput
}

export type music_playlistUncheckedCreateInput = {
  id: string
  title: string
  description?: string | null
  cover?: string | null
  sort_order?: number
  created_at?: Date | string
  updated_at?: Date | string
  songs?: Prisma.music_songUncheckedCreateNestedManyWithoutPlaylistInput
}

export type music_playlistUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cover?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sort_order?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  songs?: Prisma.music_songUpdateManyWithoutPlaylistNestedInput
}

export type music_playlistUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cover?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sort_order?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  songs?: Prisma.music_songUncheckedUpdateManyWithoutPlaylistNestedInput
}

export type music_playlistCreateManyInput = {
  id: string
  title: string
  description?: string | null
  cover?: string | null
  sort_order?: number
  created_at?: Date | string
  updated_at?: Date | string
}

export type music_playlistUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cover?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sort_order?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type music_playlistUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cover?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sort_order?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type music_playlistOrderByRelevanceInput = {
  fields:
    | Prisma.music_playlistOrderByRelevanceFieldEnum
    | Prisma.music_playlistOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type music_playlistCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  cover?: Prisma.SortOrder
  sort_order?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type music_playlistAvgOrderByAggregateInput = {
  sort_order?: Prisma.SortOrder
}

export type music_playlistMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  cover?: Prisma.SortOrder
  sort_order?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type music_playlistMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  cover?: Prisma.SortOrder
  sort_order?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
}

export type music_playlistSumOrderByAggregateInput = {
  sort_order?: Prisma.SortOrder
}

export type Music_playlistScalarRelationFilter = {
  is?: Prisma.music_playlistWhereInput
  isNot?: Prisma.music_playlistWhereInput
}

export type music_playlistCreateNestedOneWithoutSongsInput = {
  create?: Prisma.XOR<
    Prisma.music_playlistCreateWithoutSongsInput,
    Prisma.music_playlistUncheckedCreateWithoutSongsInput
  >
  connectOrCreate?: Prisma.music_playlistCreateOrConnectWithoutSongsInput
  connect?: Prisma.music_playlistWhereUniqueInput
}

export type music_playlistUpdateOneRequiredWithoutSongsNestedInput = {
  create?: Prisma.XOR<
    Prisma.music_playlistCreateWithoutSongsInput,
    Prisma.music_playlistUncheckedCreateWithoutSongsInput
  >
  connectOrCreate?: Prisma.music_playlistCreateOrConnectWithoutSongsInput
  upsert?: Prisma.music_playlistUpsertWithoutSongsInput
  connect?: Prisma.music_playlistWhereUniqueInput
  update?: Prisma.XOR<
    Prisma.XOR<
      Prisma.music_playlistUpdateToOneWithWhereWithoutSongsInput,
      Prisma.music_playlistUpdateWithoutSongsInput
    >,
    Prisma.music_playlistUncheckedUpdateWithoutSongsInput
  >
}

export type music_playlistCreateWithoutSongsInput = {
  id: string
  title: string
  description?: string | null
  cover?: string | null
  sort_order?: number
  created_at?: Date | string
  updated_at?: Date | string
}

export type music_playlistUncheckedCreateWithoutSongsInput = {
  id: string
  title: string
  description?: string | null
  cover?: string | null
  sort_order?: number
  created_at?: Date | string
  updated_at?: Date | string
}

export type music_playlistCreateOrConnectWithoutSongsInput = {
  where: Prisma.music_playlistWhereUniqueInput
  create: Prisma.XOR<
    Prisma.music_playlistCreateWithoutSongsInput,
    Prisma.music_playlistUncheckedCreateWithoutSongsInput
  >
}

export type music_playlistUpsertWithoutSongsInput = {
  update: Prisma.XOR<
    Prisma.music_playlistUpdateWithoutSongsInput,
    Prisma.music_playlistUncheckedUpdateWithoutSongsInput
  >
  create: Prisma.XOR<
    Prisma.music_playlistCreateWithoutSongsInput,
    Prisma.music_playlistUncheckedCreateWithoutSongsInput
  >
  where?: Prisma.music_playlistWhereInput
}

export type music_playlistUpdateToOneWithWhereWithoutSongsInput = {
  where?: Prisma.music_playlistWhereInput
  data: Prisma.XOR<
    Prisma.music_playlistUpdateWithoutSongsInput,
    Prisma.music_playlistUncheckedUpdateWithoutSongsInput
  >
}

export type music_playlistUpdateWithoutSongsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cover?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sort_order?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type music_playlistUncheckedUpdateWithoutSongsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cover?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sort_order?: Prisma.IntFieldUpdateOperationsInput | number
  created_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updated_at?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

/**
 * Count Type Music_playlistCountOutputType
 */

export type Music_playlistCountOutputType = {
  songs: number
}

export type Music_playlistCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  songs?: boolean | Music_playlistCountOutputTypeCountSongsArgs
}

/**
 * Music_playlistCountOutputType without action
 */
export type Music_playlistCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Music_playlistCountOutputType
   */
  select?: Prisma.Music_playlistCountOutputTypeSelect<ExtArgs> | null
}

/**
 * Music_playlistCountOutputType without action
 */
export type Music_playlistCountOutputTypeCountSongsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.music_songWhereInput
}

export type music_playlistSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    title?: boolean
    description?: boolean
    cover?: boolean
    sort_order?: boolean
    created_at?: boolean
    updated_at?: boolean
    songs?: boolean | Prisma.music_playlist$songsArgs<ExtArgs>
    _count?: boolean | Prisma.Music_playlistCountOutputTypeDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['music_playlist']
>

export type music_playlistSelectScalar = {
  id?: boolean
  title?: boolean
  description?: boolean
  cover?: boolean
  sort_order?: boolean
  created_at?: boolean
  updated_at?: boolean
}

export type music_playlistOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'id'
  | 'title'
  | 'description'
  | 'cover'
  | 'sort_order'
  | 'created_at'
  | 'updated_at',
  ExtArgs['result']['music_playlist']
>
export type music_playlistInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  songs?: boolean | Prisma.music_playlist$songsArgs<ExtArgs>
  _count?: boolean | Prisma.Music_playlistCountOutputTypeDefaultArgs<ExtArgs>
}

export type $music_playlistPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'music_playlist'
  objects: {
    songs: Prisma.$music_songPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      title: string
      description: string | null
      cover: string | null
      sort_order: number
      created_at: Date
      updated_at: Date
    },
    ExtArgs['result']['music_playlist']
  >
  composites: {}
}

export type music_playlistGetPayload<
  S extends boolean | null | undefined | music_playlistDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$music_playlistPayload, S>

export type music_playlistCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<
  music_playlistFindManyArgs,
  'select' | 'include' | 'distinct' | 'omit'
> & {
  select?: Music_playlistCountAggregateInputType | true
}

export interface music_playlistDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['music_playlist']
    meta: { name: 'music_playlist' }
  }
  /**
   * Find zero or one Music_playlist that matches the filter.
   * @param {music_playlistFindUniqueArgs} args - Arguments to find a Music_playlist
   * @example
   * // Get one Music_playlist
   * const music_playlist = await prisma.music_playlist.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends music_playlistFindUniqueArgs>(
    args: Prisma.SelectSubset<T, music_playlistFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__music_playlistClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_playlistPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one Music_playlist that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {music_playlistFindUniqueOrThrowArgs} args - Arguments to find a Music_playlist
   * @example
   * // Get one Music_playlist
   * const music_playlist = await prisma.music_playlist.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends music_playlistFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, music_playlistFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__music_playlistClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_playlistPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Music_playlist that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {music_playlistFindFirstArgs} args - Arguments to find a Music_playlist
   * @example
   * // Get one Music_playlist
   * const music_playlist = await prisma.music_playlist.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends music_playlistFindFirstArgs>(
    args?: Prisma.SelectSubset<T, music_playlistFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__music_playlistClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_playlistPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Music_playlist that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {music_playlistFindFirstOrThrowArgs} args - Arguments to find a Music_playlist
   * @example
   * // Get one Music_playlist
   * const music_playlist = await prisma.music_playlist.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends music_playlistFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, music_playlistFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__music_playlistClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_playlistPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more Music_playlists that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {music_playlistFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Music_playlists
   * const music_playlists = await prisma.music_playlist.findMany()
   *
   * // Get first 10 Music_playlists
   * const music_playlists = await prisma.music_playlist.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const music_playlistWithIdOnly = await prisma.music_playlist.findMany({ select: { id: true } })
   *
   */
  findMany<T extends music_playlistFindManyArgs>(
    args?: Prisma.SelectSubset<T, music_playlistFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$music_playlistPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a Music_playlist.
   * @param {music_playlistCreateArgs} args - Arguments to create a Music_playlist.
   * @example
   * // Create one Music_playlist
   * const Music_playlist = await prisma.music_playlist.create({
   *   data: {
   *     // ... data to create a Music_playlist
   *   }
   * })
   *
   */
  create<T extends music_playlistCreateArgs>(
    args: Prisma.SelectSubset<T, music_playlistCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__music_playlistClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_playlistPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many Music_playlists.
   * @param {music_playlistCreateManyArgs} args - Arguments to create many Music_playlists.
   * @example
   * // Create many Music_playlists
   * const music_playlist = await prisma.music_playlist.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends music_playlistCreateManyArgs>(
    args?: Prisma.SelectSubset<T, music_playlistCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Music_playlist.
   * @param {music_playlistDeleteArgs} args - Arguments to delete one Music_playlist.
   * @example
   * // Delete one Music_playlist
   * const Music_playlist = await prisma.music_playlist.delete({
   *   where: {
   *     // ... filter to delete one Music_playlist
   *   }
   * })
   *
   */
  delete<T extends music_playlistDeleteArgs>(
    args: Prisma.SelectSubset<T, music_playlistDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__music_playlistClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_playlistPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one Music_playlist.
   * @param {music_playlistUpdateArgs} args - Arguments to update one Music_playlist.
   * @example
   * // Update one Music_playlist
   * const music_playlist = await prisma.music_playlist.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends music_playlistUpdateArgs>(
    args: Prisma.SelectSubset<T, music_playlistUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__music_playlistClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_playlistPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more Music_playlists.
   * @param {music_playlistDeleteManyArgs} args - Arguments to filter Music_playlists to delete.
   * @example
   * // Delete a few Music_playlists
   * const { count } = await prisma.music_playlist.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends music_playlistDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, music_playlistDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Music_playlists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {music_playlistUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Music_playlists
   * const music_playlist = await prisma.music_playlist.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends music_playlistUpdateManyArgs>(
    args: Prisma.SelectSubset<T, music_playlistUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Music_playlist.
   * @param {music_playlistUpsertArgs} args - Arguments to update or create a Music_playlist.
   * @example
   * // Update or create a Music_playlist
   * const music_playlist = await prisma.music_playlist.upsert({
   *   create: {
   *     // ... data to create a Music_playlist
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Music_playlist we want to update
   *   }
   * })
   */
  upsert<T extends music_playlistUpsertArgs>(
    args: Prisma.SelectSubset<T, music_playlistUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__music_playlistClient<
    runtime.Types.Result.GetResult<
      Prisma.$music_playlistPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of Music_playlists.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {music_playlistCountArgs} args - Arguments to filter Music_playlists to count.
   * @example
   * // Count the number of Music_playlists
   * const count = await prisma.music_playlist.count({
   *   where: {
   *     // ... the filter for the Music_playlists we want to count
   *   }
   * })
   **/
  count<T extends music_playlistCountArgs>(
    args?: Prisma.Subset<T, music_playlistCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<
            T['select'],
            Music_playlistCountAggregateOutputType
          >
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Music_playlist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Music_playlistAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends Music_playlistAggregateArgs>(
    args: Prisma.Subset<T, Music_playlistAggregateArgs>,
  ): Prisma.PrismaPromise<GetMusic_playlistAggregateType<T>>

  /**
   * Group by Music_playlist.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {music_playlistGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends music_playlistGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends (Prisma.True extends HasSelectOrTake
      ? { orderBy: music_playlistGroupByArgs['orderBy'] }
      : { orderBy?: music_playlistGroupByArgs['orderBy'] }),
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends (T['by'] extends never[] ? Prisma.True : Prisma.False),
    InputErrors extends (ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    'Field ',
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]),
  >(
    args: Prisma.SubsetIntersection<T, music_playlistGroupByArgs, OrderByArg> &
      InputErrors,
  ): {} extends InputErrors
    ? GetMusic_playlistGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the music_playlist model
   */
  readonly fields: music_playlistFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for music_playlist.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__music_playlistClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  songs<T extends Prisma.music_playlist$songsArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.music_playlist$songsArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    | runtime.Types.Result.GetResult<
        Prisma.$music_songPayload<ExtArgs>,
        T,
        'findMany',
        GlobalOmitOptions
      >
    | Null
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the music_playlist model
 */
export interface music_playlistFieldRefs {
  readonly id: Prisma.FieldRef<'music_playlist', 'String'>
  readonly title: Prisma.FieldRef<'music_playlist', 'String'>
  readonly description: Prisma.FieldRef<'music_playlist', 'String'>
  readonly cover: Prisma.FieldRef<'music_playlist', 'String'>
  readonly sort_order: Prisma.FieldRef<'music_playlist', 'Int'>
  readonly created_at: Prisma.FieldRef<'music_playlist', 'DateTime'>
  readonly updated_at: Prisma.FieldRef<'music_playlist', 'DateTime'>
}

// Custom InputTypes
/**
 * music_playlist findUnique
 */
export type music_playlistFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_playlist
   */
  select?: Prisma.music_playlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_playlist
   */
  omit?: Prisma.music_playlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_playlistInclude<ExtArgs> | null
  /**
   * Filter, which music_playlist to fetch.
   */
  where: Prisma.music_playlistWhereUniqueInput
}

/**
 * music_playlist findUniqueOrThrow
 */
export type music_playlistFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_playlist
   */
  select?: Prisma.music_playlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_playlist
   */
  omit?: Prisma.music_playlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_playlistInclude<ExtArgs> | null
  /**
   * Filter, which music_playlist to fetch.
   */
  where: Prisma.music_playlistWhereUniqueInput
}

/**
 * music_playlist findFirst
 */
export type music_playlistFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_playlist
   */
  select?: Prisma.music_playlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_playlist
   */
  omit?: Prisma.music_playlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_playlistInclude<ExtArgs> | null
  /**
   * Filter, which music_playlist to fetch.
   */
  where?: Prisma.music_playlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of music_playlists to fetch.
   */
  orderBy?:
    | Prisma.music_playlistOrderByWithRelationInput
    | Prisma.music_playlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for music_playlists.
   */
  cursor?: Prisma.music_playlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` music_playlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` music_playlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of music_playlists.
   */
  distinct?:
    | Prisma.Music_playlistScalarFieldEnum
    | Prisma.Music_playlistScalarFieldEnum[]
}

/**
 * music_playlist findFirstOrThrow
 */
export type music_playlistFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_playlist
   */
  select?: Prisma.music_playlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_playlist
   */
  omit?: Prisma.music_playlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_playlistInclude<ExtArgs> | null
  /**
   * Filter, which music_playlist to fetch.
   */
  where?: Prisma.music_playlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of music_playlists to fetch.
   */
  orderBy?:
    | Prisma.music_playlistOrderByWithRelationInput
    | Prisma.music_playlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for music_playlists.
   */
  cursor?: Prisma.music_playlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` music_playlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` music_playlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of music_playlists.
   */
  distinct?:
    | Prisma.Music_playlistScalarFieldEnum
    | Prisma.Music_playlistScalarFieldEnum[]
}

/**
 * music_playlist findMany
 */
export type music_playlistFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_playlist
   */
  select?: Prisma.music_playlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_playlist
   */
  omit?: Prisma.music_playlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_playlistInclude<ExtArgs> | null
  /**
   * Filter, which music_playlists to fetch.
   */
  where?: Prisma.music_playlistWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of music_playlists to fetch.
   */
  orderBy?:
    | Prisma.music_playlistOrderByWithRelationInput
    | Prisma.music_playlistOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing music_playlists.
   */
  cursor?: Prisma.music_playlistWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` music_playlists from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` music_playlists.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of music_playlists.
   */
  distinct?:
    | Prisma.Music_playlistScalarFieldEnum
    | Prisma.Music_playlistScalarFieldEnum[]
}

/**
 * music_playlist create
 */
export type music_playlistCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_playlist
   */
  select?: Prisma.music_playlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_playlist
   */
  omit?: Prisma.music_playlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_playlistInclude<ExtArgs> | null
  /**
   * The data needed to create a music_playlist.
   */
  data: Prisma.XOR<
    Prisma.music_playlistCreateInput,
    Prisma.music_playlistUncheckedCreateInput
  >
}

/**
 * music_playlist createMany
 */
export type music_playlistCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many music_playlists.
   */
  data:
    | Prisma.music_playlistCreateManyInput
    | Prisma.music_playlistCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * music_playlist update
 */
export type music_playlistUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_playlist
   */
  select?: Prisma.music_playlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_playlist
   */
  omit?: Prisma.music_playlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_playlistInclude<ExtArgs> | null
  /**
   * The data needed to update a music_playlist.
   */
  data: Prisma.XOR<
    Prisma.music_playlistUpdateInput,
    Prisma.music_playlistUncheckedUpdateInput
  >
  /**
   * Choose, which music_playlist to update.
   */
  where: Prisma.music_playlistWhereUniqueInput
}

/**
 * music_playlist updateMany
 */
export type music_playlistUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update music_playlists.
   */
  data: Prisma.XOR<
    Prisma.music_playlistUpdateManyMutationInput,
    Prisma.music_playlistUncheckedUpdateManyInput
  >
  /**
   * Filter which music_playlists to update
   */
  where?: Prisma.music_playlistWhereInput
  /**
   * Limit how many music_playlists to update.
   */
  limit?: number
}

/**
 * music_playlist upsert
 */
export type music_playlistUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_playlist
   */
  select?: Prisma.music_playlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_playlist
   */
  omit?: Prisma.music_playlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_playlistInclude<ExtArgs> | null
  /**
   * The filter to search for the music_playlist to update in case it exists.
   */
  where: Prisma.music_playlistWhereUniqueInput
  /**
   * In case the music_playlist found by the `where` argument doesn't exist, create a new music_playlist with this data.
   */
  create: Prisma.XOR<
    Prisma.music_playlistCreateInput,
    Prisma.music_playlistUncheckedCreateInput
  >
  /**
   * In case the music_playlist was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.music_playlistUpdateInput,
    Prisma.music_playlistUncheckedUpdateInput
  >
}

/**
 * music_playlist delete
 */
export type music_playlistDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_playlist
   */
  select?: Prisma.music_playlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_playlist
   */
  omit?: Prisma.music_playlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_playlistInclude<ExtArgs> | null
  /**
   * Filter which music_playlist to delete.
   */
  where: Prisma.music_playlistWhereUniqueInput
}

/**
 * music_playlist deleteMany
 */
export type music_playlistDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which music_playlists to delete
   */
  where?: Prisma.music_playlistWhereInput
  /**
   * Limit how many music_playlists to delete.
   */
  limit?: number
}

/**
 * music_playlist.songs
 */
export type music_playlist$songsArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_song
   */
  select?: Prisma.music_songSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_song
   */
  omit?: Prisma.music_songOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_songInclude<ExtArgs> | null
  where?: Prisma.music_songWhereInput
  orderBy?:
    | Prisma.music_songOrderByWithRelationInput
    | Prisma.music_songOrderByWithRelationInput[]
  cursor?: Prisma.music_songWhereUniqueInput
  take?: number
  skip?: number
  distinct?:
    | Prisma.Music_songScalarFieldEnum
    | Prisma.Music_songScalarFieldEnum[]
}

/**
 * music_playlist without action
 */
export type music_playlistDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the music_playlist
   */
  select?: Prisma.music_playlistSelect<ExtArgs> | null
  /**
   * Omit specific fields from the music_playlist
   */
  omit?: Prisma.music_playlistOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.music_playlistInclude<ExtArgs> | null
}
