/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `qq_content` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums.js'
import type * as Prisma from '../internal/prismaNamespace.js'

/**
 * Model qq_content
 *
 */
export type qq_contentModel =
  runtime.Types.Result.DefaultSelection<Prisma.$qq_contentPayload>

export type AggregateQq_content = {
  _count: Qq_contentCountAggregateOutputType | null
  _avg: Qq_contentAvgAggregateOutputType | null
  _sum: Qq_contentSumAggregateOutputType | null
  _min: Qq_contentMinAggregateOutputType | null
  _max: Qq_contentMaxAggregateOutputType | null
}

export type Qq_contentAvgAggregateOutputType = {
  uin: number | null
  created_time: number | null
  lastmodify: number | null
  cmtnum: number | null
  fwdnum: number | null
  rt_sum: number | null
  videototal: number | null
  editmask: number | null
  right: number | null
  ugc_right: number | null
  t1_source: number | null
  t1_subtype: number | null
  t1_termtype: number | null
  t2_source: number | null
  t2_subtype: number | null
  t2_termtype: number | null
  wbid: number | null
}

export type Qq_contentSumAggregateOutputType = {
  uin: bigint | null
  created_time: bigint | null
  lastmodify: bigint | null
  cmtnum: number | null
  fwdnum: number | null
  rt_sum: number | null
  videototal: number | null
  editmask: number | null
  right: number | null
  ugc_right: number | null
  t1_source: number | null
  t1_subtype: number | null
  t1_termtype: number | null
  t2_source: number | null
  t2_subtype: number | null
  t2_termtype: number | null
  wbid: bigint | null
}

export type Qq_contentMinAggregateOutputType = {
  tid: string | null
  uin: bigint | null
  name: string | null
  content: string | null
  created_time: bigint | null
  create_time_str: string | null
  create_time_str2: string | null
  lastmodify: bigint | null
  source_name: string | null
  source_url: string | null
  source_appid: string | null
  conlist: string | null
  commentlist: string | null
  video: string | null
  lbs: string | null
  pic: string | null
  cmtnum: number | null
  fwdnum: number | null
  rt_sum: number | null
  videototal: number | null
  secret: boolean | null
  iseditable: boolean | null
  issigin: boolean | null
  certified: boolean | null
  editmask: number | null
  has_more_con: boolean | null
  right: number | null
  ugc_right: number | null
  pic_template: string | null
  t1_source: number | null
  t1_subtype: number | null
  t1_termtype: number | null
  t2_source: number | null
  t2_subtype: number | null
  t2_termtype: number | null
  wbid: bigint | null
  createtime: string | null
}

export type Qq_contentMaxAggregateOutputType = {
  tid: string | null
  uin: bigint | null
  name: string | null
  content: string | null
  created_time: bigint | null
  create_time_str: string | null
  create_time_str2: string | null
  lastmodify: bigint | null
  source_name: string | null
  source_url: string | null
  source_appid: string | null
  conlist: string | null
  commentlist: string | null
  video: string | null
  lbs: string | null
  pic: string | null
  cmtnum: number | null
  fwdnum: number | null
  rt_sum: number | null
  videototal: number | null
  secret: boolean | null
  iseditable: boolean | null
  issigin: boolean | null
  certified: boolean | null
  editmask: number | null
  has_more_con: boolean | null
  right: number | null
  ugc_right: number | null
  pic_template: string | null
  t1_source: number | null
  t1_subtype: number | null
  t1_termtype: number | null
  t2_source: number | null
  t2_subtype: number | null
  t2_termtype: number | null
  wbid: bigint | null
  createtime: string | null
}

export type Qq_contentCountAggregateOutputType = {
  tid: number
  uin: number
  name: number
  content: number
  created_time: number
  create_time_str: number
  create_time_str2: number
  lastmodify: number
  source_name: number
  source_url: number
  source_appid: number
  conlist: number
  commentlist: number
  video: number
  lbs: number
  pic: number
  cmtnum: number
  fwdnum: number
  rt_sum: number
  videototal: number
  secret: number
  iseditable: number
  issigin: number
  certified: number
  editmask: number
  has_more_con: number
  right: number
  ugc_right: number
  pic_template: number
  t1_source: number
  t1_subtype: number
  t1_termtype: number
  t2_source: number
  t2_subtype: number
  t2_termtype: number
  wbid: number
  createtime: number
  _all: number
}

export type Qq_contentAvgAggregateInputType = {
  uin?: true
  created_time?: true
  lastmodify?: true
  cmtnum?: true
  fwdnum?: true
  rt_sum?: true
  videototal?: true
  editmask?: true
  right?: true
  ugc_right?: true
  t1_source?: true
  t1_subtype?: true
  t1_termtype?: true
  t2_source?: true
  t2_subtype?: true
  t2_termtype?: true
  wbid?: true
}

export type Qq_contentSumAggregateInputType = {
  uin?: true
  created_time?: true
  lastmodify?: true
  cmtnum?: true
  fwdnum?: true
  rt_sum?: true
  videototal?: true
  editmask?: true
  right?: true
  ugc_right?: true
  t1_source?: true
  t1_subtype?: true
  t1_termtype?: true
  t2_source?: true
  t2_subtype?: true
  t2_termtype?: true
  wbid?: true
}

export type Qq_contentMinAggregateInputType = {
  tid?: true
  uin?: true
  name?: true
  content?: true
  created_time?: true
  create_time_str?: true
  create_time_str2?: true
  lastmodify?: true
  source_name?: true
  source_url?: true
  source_appid?: true
  conlist?: true
  commentlist?: true
  video?: true
  lbs?: true
  pic?: true
  cmtnum?: true
  fwdnum?: true
  rt_sum?: true
  videototal?: true
  secret?: true
  iseditable?: true
  issigin?: true
  certified?: true
  editmask?: true
  has_more_con?: true
  right?: true
  ugc_right?: true
  pic_template?: true
  t1_source?: true
  t1_subtype?: true
  t1_termtype?: true
  t2_source?: true
  t2_subtype?: true
  t2_termtype?: true
  wbid?: true
  createtime?: true
}

export type Qq_contentMaxAggregateInputType = {
  tid?: true
  uin?: true
  name?: true
  content?: true
  created_time?: true
  create_time_str?: true
  create_time_str2?: true
  lastmodify?: true
  source_name?: true
  source_url?: true
  source_appid?: true
  conlist?: true
  commentlist?: true
  video?: true
  lbs?: true
  pic?: true
  cmtnum?: true
  fwdnum?: true
  rt_sum?: true
  videototal?: true
  secret?: true
  iseditable?: true
  issigin?: true
  certified?: true
  editmask?: true
  has_more_con?: true
  right?: true
  ugc_right?: true
  pic_template?: true
  t1_source?: true
  t1_subtype?: true
  t1_termtype?: true
  t2_source?: true
  t2_subtype?: true
  t2_termtype?: true
  wbid?: true
  createtime?: true
}

export type Qq_contentCountAggregateInputType = {
  tid?: true
  uin?: true
  name?: true
  content?: true
  created_time?: true
  create_time_str?: true
  create_time_str2?: true
  lastmodify?: true
  source_name?: true
  source_url?: true
  source_appid?: true
  conlist?: true
  commentlist?: true
  video?: true
  lbs?: true
  pic?: true
  cmtnum?: true
  fwdnum?: true
  rt_sum?: true
  videototal?: true
  secret?: true
  iseditable?: true
  issigin?: true
  certified?: true
  editmask?: true
  has_more_con?: true
  right?: true
  ugc_right?: true
  pic_template?: true
  t1_source?: true
  t1_subtype?: true
  t1_termtype?: true
  t2_source?: true
  t2_subtype?: true
  t2_termtype?: true
  wbid?: true
  createtime?: true
  _all?: true
}

export type Qq_contentAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which qq_content to aggregate.
   */
  where?: Prisma.qq_contentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of qq_contents to fetch.
   */
  orderBy?:
    | Prisma.qq_contentOrderByWithRelationInput
    | Prisma.qq_contentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.qq_contentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` qq_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` qq_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned qq_contents
   **/
  _count?: true | Qq_contentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: Qq_contentAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: Qq_contentSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: Qq_contentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: Qq_contentMaxAggregateInputType
}

export type GetQq_contentAggregateType<T extends Qq_contentAggregateArgs> = {
  [P in keyof T & keyof AggregateQq_content]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateQq_content[P]>
    : Prisma.GetScalarType<T[P], AggregateQq_content[P]>
}

export type qq_contentGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.qq_contentWhereInput
  orderBy?:
    | Prisma.qq_contentOrderByWithAggregationInput
    | Prisma.qq_contentOrderByWithAggregationInput[]
  by: Prisma.Qq_contentScalarFieldEnum[] | Prisma.Qq_contentScalarFieldEnum
  having?: Prisma.qq_contentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Qq_contentCountAggregateInputType | true
  _avg?: Qq_contentAvgAggregateInputType
  _sum?: Qq_contentSumAggregateInputType
  _min?: Qq_contentMinAggregateInputType
  _max?: Qq_contentMaxAggregateInputType
}

export type Qq_contentGroupByOutputType = {
  tid: string
  uin: bigint | null
  name: string | null
  content: string | null
  created_time: bigint | null
  create_time_str: string | null
  create_time_str2: string | null
  lastmodify: bigint | null
  source_name: string | null
  source_url: string | null
  source_appid: string | null
  conlist: string | null
  commentlist: string | null
  video: string | null
  lbs: string | null
  pic: string | null
  cmtnum: number | null
  fwdnum: number | null
  rt_sum: number | null
  videototal: number | null
  secret: boolean | null
  iseditable: boolean | null
  issigin: boolean | null
  certified: boolean | null
  editmask: number | null
  has_more_con: boolean | null
  right: number | null
  ugc_right: number | null
  pic_template: string | null
  t1_source: number | null
  t1_subtype: number | null
  t1_termtype: number | null
  t2_source: number | null
  t2_subtype: number | null
  t2_termtype: number | null
  wbid: bigint | null
  createtime: string | null
  _count: Qq_contentCountAggregateOutputType | null
  _avg: Qq_contentAvgAggregateOutputType | null
  _sum: Qq_contentSumAggregateOutputType | null
  _min: Qq_contentMinAggregateOutputType | null
  _max: Qq_contentMaxAggregateOutputType | null
}

export type GetQq_contentGroupByPayload<T extends qq_contentGroupByArgs> =
  Prisma.PrismaPromise<
    Array<
      Prisma.PickEnumerable<Qq_contentGroupByOutputType, T['by']> & {
        [P in keyof T & keyof Qq_contentGroupByOutputType]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Qq_contentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Qq_contentGroupByOutputType[P]>
      }
    >
  >

export type qq_contentWhereInput = {
  AND?: Prisma.qq_contentWhereInput | Prisma.qq_contentWhereInput[]
  OR?: Prisma.qq_contentWhereInput[]
  NOT?: Prisma.qq_contentWhereInput | Prisma.qq_contentWhereInput[]
  tid?: Prisma.StringFilter<'qq_content'> | string
  uin?: Prisma.BigIntNullableFilter<'qq_content'> | bigint | number | null
  name?: Prisma.StringNullableFilter<'qq_content'> | string | null
  content?: Prisma.StringNullableFilter<'qq_content'> | string | null
  created_time?:
    | Prisma.BigIntNullableFilter<'qq_content'>
    | bigint
    | number
    | null
  create_time_str?: Prisma.StringNullableFilter<'qq_content'> | string | null
  create_time_str2?: Prisma.StringNullableFilter<'qq_content'> | string | null
  lastmodify?:
    | Prisma.BigIntNullableFilter<'qq_content'>
    | bigint
    | number
    | null
  source_name?: Prisma.StringNullableFilter<'qq_content'> | string | null
  source_url?: Prisma.StringNullableFilter<'qq_content'> | string | null
  source_appid?: Prisma.StringNullableFilter<'qq_content'> | string | null
  conlist?: Prisma.StringNullableFilter<'qq_content'> | string | null
  commentlist?: Prisma.StringNullableFilter<'qq_content'> | string | null
  video?: Prisma.StringNullableFilter<'qq_content'> | string | null
  lbs?: Prisma.StringNullableFilter<'qq_content'> | string | null
  pic?: Prisma.StringNullableFilter<'qq_content'> | string | null
  cmtnum?: Prisma.IntNullableFilter<'qq_content'> | number | null
  fwdnum?: Prisma.IntNullableFilter<'qq_content'> | number | null
  rt_sum?: Prisma.IntNullableFilter<'qq_content'> | number | null
  videototal?: Prisma.IntNullableFilter<'qq_content'> | number | null
  secret?: Prisma.BoolNullableFilter<'qq_content'> | boolean | null
  iseditable?: Prisma.BoolNullableFilter<'qq_content'> | boolean | null
  issigin?: Prisma.BoolNullableFilter<'qq_content'> | boolean | null
  certified?: Prisma.BoolNullableFilter<'qq_content'> | boolean | null
  editmask?: Prisma.IntNullableFilter<'qq_content'> | number | null
  has_more_con?: Prisma.BoolNullableFilter<'qq_content'> | boolean | null
  right?: Prisma.IntNullableFilter<'qq_content'> | number | null
  ugc_right?: Prisma.IntNullableFilter<'qq_content'> | number | null
  pic_template?: Prisma.StringNullableFilter<'qq_content'> | string | null
  t1_source?: Prisma.IntNullableFilter<'qq_content'> | number | null
  t1_subtype?: Prisma.IntNullableFilter<'qq_content'> | number | null
  t1_termtype?: Prisma.IntNullableFilter<'qq_content'> | number | null
  t2_source?: Prisma.IntNullableFilter<'qq_content'> | number | null
  t2_subtype?: Prisma.IntNullableFilter<'qq_content'> | number | null
  t2_termtype?: Prisma.IntNullableFilter<'qq_content'> | number | null
  wbid?: Prisma.BigIntNullableFilter<'qq_content'> | bigint | number | null
  createtime?: Prisma.StringNullableFilter<'qq_content'> | string | null
}

export type qq_contentOrderByWithRelationInput = {
  tid?: Prisma.SortOrder
  uin?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  content?: Prisma.SortOrderInput | Prisma.SortOrder
  created_time?: Prisma.SortOrderInput | Prisma.SortOrder
  create_time_str?: Prisma.SortOrderInput | Prisma.SortOrder
  create_time_str2?: Prisma.SortOrderInput | Prisma.SortOrder
  lastmodify?: Prisma.SortOrderInput | Prisma.SortOrder
  source_name?: Prisma.SortOrderInput | Prisma.SortOrder
  source_url?: Prisma.SortOrderInput | Prisma.SortOrder
  source_appid?: Prisma.SortOrderInput | Prisma.SortOrder
  conlist?: Prisma.SortOrderInput | Prisma.SortOrder
  commentlist?: Prisma.SortOrderInput | Prisma.SortOrder
  video?: Prisma.SortOrderInput | Prisma.SortOrder
  lbs?: Prisma.SortOrderInput | Prisma.SortOrder
  pic?: Prisma.SortOrderInput | Prisma.SortOrder
  cmtnum?: Prisma.SortOrderInput | Prisma.SortOrder
  fwdnum?: Prisma.SortOrderInput | Prisma.SortOrder
  rt_sum?: Prisma.SortOrderInput | Prisma.SortOrder
  videototal?: Prisma.SortOrderInput | Prisma.SortOrder
  secret?: Prisma.SortOrderInput | Prisma.SortOrder
  iseditable?: Prisma.SortOrderInput | Prisma.SortOrder
  issigin?: Prisma.SortOrderInput | Prisma.SortOrder
  certified?: Prisma.SortOrderInput | Prisma.SortOrder
  editmask?: Prisma.SortOrderInput | Prisma.SortOrder
  has_more_con?: Prisma.SortOrderInput | Prisma.SortOrder
  right?: Prisma.SortOrderInput | Prisma.SortOrder
  ugc_right?: Prisma.SortOrderInput | Prisma.SortOrder
  pic_template?: Prisma.SortOrderInput | Prisma.SortOrder
  t1_source?: Prisma.SortOrderInput | Prisma.SortOrder
  t1_subtype?: Prisma.SortOrderInput | Prisma.SortOrder
  t1_termtype?: Prisma.SortOrderInput | Prisma.SortOrder
  t2_source?: Prisma.SortOrderInput | Prisma.SortOrder
  t2_subtype?: Prisma.SortOrderInput | Prisma.SortOrder
  t2_termtype?: Prisma.SortOrderInput | Prisma.SortOrder
  wbid?: Prisma.SortOrderInput | Prisma.SortOrder
  createtime?: Prisma.SortOrderInput | Prisma.SortOrder
  _relevance?: Prisma.qq_contentOrderByRelevanceInput
}

export type qq_contentWhereUniqueInput = Prisma.AtLeast<
  {
    tid?: string
    AND?: Prisma.qq_contentWhereInput | Prisma.qq_contentWhereInput[]
    OR?: Prisma.qq_contentWhereInput[]
    NOT?: Prisma.qq_contentWhereInput | Prisma.qq_contentWhereInput[]
    uin?: Prisma.BigIntNullableFilter<'qq_content'> | bigint | number | null
    name?: Prisma.StringNullableFilter<'qq_content'> | string | null
    content?: Prisma.StringNullableFilter<'qq_content'> | string | null
    created_time?:
      | Prisma.BigIntNullableFilter<'qq_content'>
      | bigint
      | number
      | null
    create_time_str?: Prisma.StringNullableFilter<'qq_content'> | string | null
    create_time_str2?: Prisma.StringNullableFilter<'qq_content'> | string | null
    lastmodify?:
      | Prisma.BigIntNullableFilter<'qq_content'>
      | bigint
      | number
      | null
    source_name?: Prisma.StringNullableFilter<'qq_content'> | string | null
    source_url?: Prisma.StringNullableFilter<'qq_content'> | string | null
    source_appid?: Prisma.StringNullableFilter<'qq_content'> | string | null
    conlist?: Prisma.StringNullableFilter<'qq_content'> | string | null
    commentlist?: Prisma.StringNullableFilter<'qq_content'> | string | null
    video?: Prisma.StringNullableFilter<'qq_content'> | string | null
    lbs?: Prisma.StringNullableFilter<'qq_content'> | string | null
    pic?: Prisma.StringNullableFilter<'qq_content'> | string | null
    cmtnum?: Prisma.IntNullableFilter<'qq_content'> | number | null
    fwdnum?: Prisma.IntNullableFilter<'qq_content'> | number | null
    rt_sum?: Prisma.IntNullableFilter<'qq_content'> | number | null
    videototal?: Prisma.IntNullableFilter<'qq_content'> | number | null
    secret?: Prisma.BoolNullableFilter<'qq_content'> | boolean | null
    iseditable?: Prisma.BoolNullableFilter<'qq_content'> | boolean | null
    issigin?: Prisma.BoolNullableFilter<'qq_content'> | boolean | null
    certified?: Prisma.BoolNullableFilter<'qq_content'> | boolean | null
    editmask?: Prisma.IntNullableFilter<'qq_content'> | number | null
    has_more_con?: Prisma.BoolNullableFilter<'qq_content'> | boolean | null
    right?: Prisma.IntNullableFilter<'qq_content'> | number | null
    ugc_right?: Prisma.IntNullableFilter<'qq_content'> | number | null
    pic_template?: Prisma.StringNullableFilter<'qq_content'> | string | null
    t1_source?: Prisma.IntNullableFilter<'qq_content'> | number | null
    t1_subtype?: Prisma.IntNullableFilter<'qq_content'> | number | null
    t1_termtype?: Prisma.IntNullableFilter<'qq_content'> | number | null
    t2_source?: Prisma.IntNullableFilter<'qq_content'> | number | null
    t2_subtype?: Prisma.IntNullableFilter<'qq_content'> | number | null
    t2_termtype?: Prisma.IntNullableFilter<'qq_content'> | number | null
    wbid?: Prisma.BigIntNullableFilter<'qq_content'> | bigint | number | null
    createtime?: Prisma.StringNullableFilter<'qq_content'> | string | null
  },
  'tid'
>

export type qq_contentOrderByWithAggregationInput = {
  tid?: Prisma.SortOrder
  uin?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrderInput | Prisma.SortOrder
  content?: Prisma.SortOrderInput | Prisma.SortOrder
  created_time?: Prisma.SortOrderInput | Prisma.SortOrder
  create_time_str?: Prisma.SortOrderInput | Prisma.SortOrder
  create_time_str2?: Prisma.SortOrderInput | Prisma.SortOrder
  lastmodify?: Prisma.SortOrderInput | Prisma.SortOrder
  source_name?: Prisma.SortOrderInput | Prisma.SortOrder
  source_url?: Prisma.SortOrderInput | Prisma.SortOrder
  source_appid?: Prisma.SortOrderInput | Prisma.SortOrder
  conlist?: Prisma.SortOrderInput | Prisma.SortOrder
  commentlist?: Prisma.SortOrderInput | Prisma.SortOrder
  video?: Prisma.SortOrderInput | Prisma.SortOrder
  lbs?: Prisma.SortOrderInput | Prisma.SortOrder
  pic?: Prisma.SortOrderInput | Prisma.SortOrder
  cmtnum?: Prisma.SortOrderInput | Prisma.SortOrder
  fwdnum?: Prisma.SortOrderInput | Prisma.SortOrder
  rt_sum?: Prisma.SortOrderInput | Prisma.SortOrder
  videototal?: Prisma.SortOrderInput | Prisma.SortOrder
  secret?: Prisma.SortOrderInput | Prisma.SortOrder
  iseditable?: Prisma.SortOrderInput | Prisma.SortOrder
  issigin?: Prisma.SortOrderInput | Prisma.SortOrder
  certified?: Prisma.SortOrderInput | Prisma.SortOrder
  editmask?: Prisma.SortOrderInput | Prisma.SortOrder
  has_more_con?: Prisma.SortOrderInput | Prisma.SortOrder
  right?: Prisma.SortOrderInput | Prisma.SortOrder
  ugc_right?: Prisma.SortOrderInput | Prisma.SortOrder
  pic_template?: Prisma.SortOrderInput | Prisma.SortOrder
  t1_source?: Prisma.SortOrderInput | Prisma.SortOrder
  t1_subtype?: Prisma.SortOrderInput | Prisma.SortOrder
  t1_termtype?: Prisma.SortOrderInput | Prisma.SortOrder
  t2_source?: Prisma.SortOrderInput | Prisma.SortOrder
  t2_subtype?: Prisma.SortOrderInput | Prisma.SortOrder
  t2_termtype?: Prisma.SortOrderInput | Prisma.SortOrder
  wbid?: Prisma.SortOrderInput | Prisma.SortOrder
  createtime?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.qq_contentCountOrderByAggregateInput
  _avg?: Prisma.qq_contentAvgOrderByAggregateInput
  _max?: Prisma.qq_contentMaxOrderByAggregateInput
  _min?: Prisma.qq_contentMinOrderByAggregateInput
  _sum?: Prisma.qq_contentSumOrderByAggregateInput
}

export type qq_contentScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.qq_contentScalarWhereWithAggregatesInput
    | Prisma.qq_contentScalarWhereWithAggregatesInput[]
  OR?: Prisma.qq_contentScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.qq_contentScalarWhereWithAggregatesInput
    | Prisma.qq_contentScalarWhereWithAggregatesInput[]
  tid?: Prisma.StringWithAggregatesFilter<'qq_content'> | string
  uin?:
    | Prisma.BigIntNullableWithAggregatesFilter<'qq_content'>
    | bigint
    | number
    | null
  name?: Prisma.StringNullableWithAggregatesFilter<'qq_content'> | string | null
  content?:
    | Prisma.StringNullableWithAggregatesFilter<'qq_content'>
    | string
    | null
  created_time?:
    | Prisma.BigIntNullableWithAggregatesFilter<'qq_content'>
    | bigint
    | number
    | null
  create_time_str?:
    | Prisma.StringNullableWithAggregatesFilter<'qq_content'>
    | string
    | null
  create_time_str2?:
    | Prisma.StringNullableWithAggregatesFilter<'qq_content'>
    | string
    | null
  lastmodify?:
    | Prisma.BigIntNullableWithAggregatesFilter<'qq_content'>
    | bigint
    | number
    | null
  source_name?:
    | Prisma.StringNullableWithAggregatesFilter<'qq_content'>
    | string
    | null
  source_url?:
    | Prisma.StringNullableWithAggregatesFilter<'qq_content'>
    | string
    | null
  source_appid?:
    | Prisma.StringNullableWithAggregatesFilter<'qq_content'>
    | string
    | null
  conlist?:
    | Prisma.StringNullableWithAggregatesFilter<'qq_content'>
    | string
    | null
  commentlist?:
    | Prisma.StringNullableWithAggregatesFilter<'qq_content'>
    | string
    | null
  video?:
    | Prisma.StringNullableWithAggregatesFilter<'qq_content'>
    | string
    | null
  lbs?: Prisma.StringNullableWithAggregatesFilter<'qq_content'> | string | null
  pic?: Prisma.StringNullableWithAggregatesFilter<'qq_content'> | string | null
  cmtnum?: Prisma.IntNullableWithAggregatesFilter<'qq_content'> | number | null
  fwdnum?: Prisma.IntNullableWithAggregatesFilter<'qq_content'> | number | null
  rt_sum?: Prisma.IntNullableWithAggregatesFilter<'qq_content'> | number | null
  videototal?:
    | Prisma.IntNullableWithAggregatesFilter<'qq_content'>
    | number
    | null
  secret?:
    | Prisma.BoolNullableWithAggregatesFilter<'qq_content'>
    | boolean
    | null
  iseditable?:
    | Prisma.BoolNullableWithAggregatesFilter<'qq_content'>
    | boolean
    | null
  issigin?:
    | Prisma.BoolNullableWithAggregatesFilter<'qq_content'>
    | boolean
    | null
  certified?:
    | Prisma.BoolNullableWithAggregatesFilter<'qq_content'>
    | boolean
    | null
  editmask?:
    | Prisma.IntNullableWithAggregatesFilter<'qq_content'>
    | number
    | null
  has_more_con?:
    | Prisma.BoolNullableWithAggregatesFilter<'qq_content'>
    | boolean
    | null
  right?: Prisma.IntNullableWithAggregatesFilter<'qq_content'> | number | null
  ugc_right?:
    | Prisma.IntNullableWithAggregatesFilter<'qq_content'>
    | number
    | null
  pic_template?:
    | Prisma.StringNullableWithAggregatesFilter<'qq_content'>
    | string
    | null
  t1_source?:
    | Prisma.IntNullableWithAggregatesFilter<'qq_content'>
    | number
    | null
  t1_subtype?:
    | Prisma.IntNullableWithAggregatesFilter<'qq_content'>
    | number
    | null
  t1_termtype?:
    | Prisma.IntNullableWithAggregatesFilter<'qq_content'>
    | number
    | null
  t2_source?:
    | Prisma.IntNullableWithAggregatesFilter<'qq_content'>
    | number
    | null
  t2_subtype?:
    | Prisma.IntNullableWithAggregatesFilter<'qq_content'>
    | number
    | null
  t2_termtype?:
    | Prisma.IntNullableWithAggregatesFilter<'qq_content'>
    | number
    | null
  wbid?:
    | Prisma.BigIntNullableWithAggregatesFilter<'qq_content'>
    | bigint
    | number
    | null
  createtime?:
    | Prisma.StringNullableWithAggregatesFilter<'qq_content'>
    | string
    | null
}

export type qq_contentCreateInput = {
  tid: string
  uin?: bigint | number | null
  name?: string | null
  content?: string | null
  created_time?: bigint | number | null
  create_time_str?: string | null
  create_time_str2?: string | null
  lastmodify?: bigint | number | null
  source_name?: string | null
  source_url?: string | null
  source_appid?: string | null
  conlist?: string | null
  commentlist?: string | null
  video?: string | null
  lbs?: string | null
  pic?: string | null
  cmtnum?: number | null
  fwdnum?: number | null
  rt_sum?: number | null
  videototal?: number | null
  secret?: boolean | null
  iseditable?: boolean | null
  issigin?: boolean | null
  certified?: boolean | null
  editmask?: number | null
  has_more_con?: boolean | null
  right?: number | null
  ugc_right?: number | null
  pic_template?: string | null
  t1_source?: number | null
  t1_subtype?: number | null
  t1_termtype?: number | null
  t2_source?: number | null
  t2_subtype?: number | null
  t2_termtype?: number | null
  wbid?: bigint | number | null
  createtime?: string | null
}

export type qq_contentUncheckedCreateInput = {
  tid: string
  uin?: bigint | number | null
  name?: string | null
  content?: string | null
  created_time?: bigint | number | null
  create_time_str?: string | null
  create_time_str2?: string | null
  lastmodify?: bigint | number | null
  source_name?: string | null
  source_url?: string | null
  source_appid?: string | null
  conlist?: string | null
  commentlist?: string | null
  video?: string | null
  lbs?: string | null
  pic?: string | null
  cmtnum?: number | null
  fwdnum?: number | null
  rt_sum?: number | null
  videototal?: number | null
  secret?: boolean | null
  iseditable?: boolean | null
  issigin?: boolean | null
  certified?: boolean | null
  editmask?: number | null
  has_more_con?: boolean | null
  right?: number | null
  ugc_right?: number | null
  pic_template?: string | null
  t1_source?: number | null
  t1_subtype?: number | null
  t1_termtype?: number | null
  t2_source?: number | null
  t2_subtype?: number | null
  t2_termtype?: number | null
  wbid?: bigint | number | null
  createtime?: string | null
}

export type qq_contentUpdateInput = {
  tid?: Prisma.StringFieldUpdateOperationsInput | string
  uin?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_time?:
    | Prisma.NullableBigIntFieldUpdateOperationsInput
    | bigint
    | number
    | null
  create_time_str?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  create_time_str2?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  lastmodify?:
    | Prisma.NullableBigIntFieldUpdateOperationsInput
    | bigint
    | number
    | null
  source_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_appid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conlist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentlist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lbs?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cmtnum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fwdnum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  rt_sum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  videototal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  secret?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  iseditable?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  issigin?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  certified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  editmask?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  has_more_con?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  right?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ugc_right?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pic_template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  t1_source?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t1_subtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t1_termtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t2_source?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t2_subtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t2_termtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  wbid?:
    | Prisma.NullableBigIntFieldUpdateOperationsInput
    | bigint
    | number
    | null
  createtime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type qq_contentUncheckedUpdateInput = {
  tid?: Prisma.StringFieldUpdateOperationsInput | string
  uin?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_time?:
    | Prisma.NullableBigIntFieldUpdateOperationsInput
    | bigint
    | number
    | null
  create_time_str?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  create_time_str2?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  lastmodify?:
    | Prisma.NullableBigIntFieldUpdateOperationsInput
    | bigint
    | number
    | null
  source_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_appid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conlist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentlist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lbs?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cmtnum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fwdnum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  rt_sum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  videototal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  secret?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  iseditable?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  issigin?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  certified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  editmask?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  has_more_con?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  right?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ugc_right?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pic_template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  t1_source?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t1_subtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t1_termtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t2_source?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t2_subtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t2_termtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  wbid?:
    | Prisma.NullableBigIntFieldUpdateOperationsInput
    | bigint
    | number
    | null
  createtime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type qq_contentCreateManyInput = {
  tid: string
  uin?: bigint | number | null
  name?: string | null
  content?: string | null
  created_time?: bigint | number | null
  create_time_str?: string | null
  create_time_str2?: string | null
  lastmodify?: bigint | number | null
  source_name?: string | null
  source_url?: string | null
  source_appid?: string | null
  conlist?: string | null
  commentlist?: string | null
  video?: string | null
  lbs?: string | null
  pic?: string | null
  cmtnum?: number | null
  fwdnum?: number | null
  rt_sum?: number | null
  videototal?: number | null
  secret?: boolean | null
  iseditable?: boolean | null
  issigin?: boolean | null
  certified?: boolean | null
  editmask?: number | null
  has_more_con?: boolean | null
  right?: number | null
  ugc_right?: number | null
  pic_template?: string | null
  t1_source?: number | null
  t1_subtype?: number | null
  t1_termtype?: number | null
  t2_source?: number | null
  t2_subtype?: number | null
  t2_termtype?: number | null
  wbid?: bigint | number | null
  createtime?: string | null
}

export type qq_contentUpdateManyMutationInput = {
  tid?: Prisma.StringFieldUpdateOperationsInput | string
  uin?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_time?:
    | Prisma.NullableBigIntFieldUpdateOperationsInput
    | bigint
    | number
    | null
  create_time_str?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  create_time_str2?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  lastmodify?:
    | Prisma.NullableBigIntFieldUpdateOperationsInput
    | bigint
    | number
    | null
  source_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_appid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conlist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentlist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lbs?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cmtnum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fwdnum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  rt_sum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  videototal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  secret?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  iseditable?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  issigin?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  certified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  editmask?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  has_more_con?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  right?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ugc_right?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pic_template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  t1_source?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t1_subtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t1_termtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t2_source?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t2_subtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t2_termtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  wbid?:
    | Prisma.NullableBigIntFieldUpdateOperationsInput
    | bigint
    | number
    | null
  createtime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type qq_contentUncheckedUpdateManyInput = {
  tid?: Prisma.StringFieldUpdateOperationsInput | string
  uin?: Prisma.NullableBigIntFieldUpdateOperationsInput | bigint | number | null
  name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  content?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_time?:
    | Prisma.NullableBigIntFieldUpdateOperationsInput
    | bigint
    | number
    | null
  create_time_str?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  create_time_str2?:
    | Prisma.NullableStringFieldUpdateOperationsInput
    | string
    | null
  lastmodify?:
    | Prisma.NullableBigIntFieldUpdateOperationsInput
    | bigint
    | number
    | null
  source_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_url?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source_appid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  conlist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  commentlist?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  video?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lbs?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  pic?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  cmtnum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  fwdnum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  rt_sum?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  videototal?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  secret?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  iseditable?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  issigin?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  certified?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  editmask?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  has_more_con?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  right?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  ugc_right?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  pic_template?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  t1_source?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t1_subtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t1_termtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t2_source?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t2_subtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  t2_termtype?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  wbid?:
    | Prisma.NullableBigIntFieldUpdateOperationsInput
    | bigint
    | number
    | null
  createtime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type qq_contentOrderByRelevanceInput = {
  fields:
    | Prisma.qq_contentOrderByRelevanceFieldEnum
    | Prisma.qq_contentOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type qq_contentCountOrderByAggregateInput = {
  tid?: Prisma.SortOrder
  uin?: Prisma.SortOrder
  name?: Prisma.SortOrder
  content?: Prisma.SortOrder
  created_time?: Prisma.SortOrder
  create_time_str?: Prisma.SortOrder
  create_time_str2?: Prisma.SortOrder
  lastmodify?: Prisma.SortOrder
  source_name?: Prisma.SortOrder
  source_url?: Prisma.SortOrder
  source_appid?: Prisma.SortOrder
  conlist?: Prisma.SortOrder
  commentlist?: Prisma.SortOrder
  video?: Prisma.SortOrder
  lbs?: Prisma.SortOrder
  pic?: Prisma.SortOrder
  cmtnum?: Prisma.SortOrder
  fwdnum?: Prisma.SortOrder
  rt_sum?: Prisma.SortOrder
  videototal?: Prisma.SortOrder
  secret?: Prisma.SortOrder
  iseditable?: Prisma.SortOrder
  issigin?: Prisma.SortOrder
  certified?: Prisma.SortOrder
  editmask?: Prisma.SortOrder
  has_more_con?: Prisma.SortOrder
  right?: Prisma.SortOrder
  ugc_right?: Prisma.SortOrder
  pic_template?: Prisma.SortOrder
  t1_source?: Prisma.SortOrder
  t1_subtype?: Prisma.SortOrder
  t1_termtype?: Prisma.SortOrder
  t2_source?: Prisma.SortOrder
  t2_subtype?: Prisma.SortOrder
  t2_termtype?: Prisma.SortOrder
  wbid?: Prisma.SortOrder
  createtime?: Prisma.SortOrder
}

export type qq_contentAvgOrderByAggregateInput = {
  uin?: Prisma.SortOrder
  created_time?: Prisma.SortOrder
  lastmodify?: Prisma.SortOrder
  cmtnum?: Prisma.SortOrder
  fwdnum?: Prisma.SortOrder
  rt_sum?: Prisma.SortOrder
  videototal?: Prisma.SortOrder
  editmask?: Prisma.SortOrder
  right?: Prisma.SortOrder
  ugc_right?: Prisma.SortOrder
  t1_source?: Prisma.SortOrder
  t1_subtype?: Prisma.SortOrder
  t1_termtype?: Prisma.SortOrder
  t2_source?: Prisma.SortOrder
  t2_subtype?: Prisma.SortOrder
  t2_termtype?: Prisma.SortOrder
  wbid?: Prisma.SortOrder
}

export type qq_contentMaxOrderByAggregateInput = {
  tid?: Prisma.SortOrder
  uin?: Prisma.SortOrder
  name?: Prisma.SortOrder
  content?: Prisma.SortOrder
  created_time?: Prisma.SortOrder
  create_time_str?: Prisma.SortOrder
  create_time_str2?: Prisma.SortOrder
  lastmodify?: Prisma.SortOrder
  source_name?: Prisma.SortOrder
  source_url?: Prisma.SortOrder
  source_appid?: Prisma.SortOrder
  conlist?: Prisma.SortOrder
  commentlist?: Prisma.SortOrder
  video?: Prisma.SortOrder
  lbs?: Prisma.SortOrder
  pic?: Prisma.SortOrder
  cmtnum?: Prisma.SortOrder
  fwdnum?: Prisma.SortOrder
  rt_sum?: Prisma.SortOrder
  videototal?: Prisma.SortOrder
  secret?: Prisma.SortOrder
  iseditable?: Prisma.SortOrder
  issigin?: Prisma.SortOrder
  certified?: Prisma.SortOrder
  editmask?: Prisma.SortOrder
  has_more_con?: Prisma.SortOrder
  right?: Prisma.SortOrder
  ugc_right?: Prisma.SortOrder
  pic_template?: Prisma.SortOrder
  t1_source?: Prisma.SortOrder
  t1_subtype?: Prisma.SortOrder
  t1_termtype?: Prisma.SortOrder
  t2_source?: Prisma.SortOrder
  t2_subtype?: Prisma.SortOrder
  t2_termtype?: Prisma.SortOrder
  wbid?: Prisma.SortOrder
  createtime?: Prisma.SortOrder
}

export type qq_contentMinOrderByAggregateInput = {
  tid?: Prisma.SortOrder
  uin?: Prisma.SortOrder
  name?: Prisma.SortOrder
  content?: Prisma.SortOrder
  created_time?: Prisma.SortOrder
  create_time_str?: Prisma.SortOrder
  create_time_str2?: Prisma.SortOrder
  lastmodify?: Prisma.SortOrder
  source_name?: Prisma.SortOrder
  source_url?: Prisma.SortOrder
  source_appid?: Prisma.SortOrder
  conlist?: Prisma.SortOrder
  commentlist?: Prisma.SortOrder
  video?: Prisma.SortOrder
  lbs?: Prisma.SortOrder
  pic?: Prisma.SortOrder
  cmtnum?: Prisma.SortOrder
  fwdnum?: Prisma.SortOrder
  rt_sum?: Prisma.SortOrder
  videototal?: Prisma.SortOrder
  secret?: Prisma.SortOrder
  iseditable?: Prisma.SortOrder
  issigin?: Prisma.SortOrder
  certified?: Prisma.SortOrder
  editmask?: Prisma.SortOrder
  has_more_con?: Prisma.SortOrder
  right?: Prisma.SortOrder
  ugc_right?: Prisma.SortOrder
  pic_template?: Prisma.SortOrder
  t1_source?: Prisma.SortOrder
  t1_subtype?: Prisma.SortOrder
  t1_termtype?: Prisma.SortOrder
  t2_source?: Prisma.SortOrder
  t2_subtype?: Prisma.SortOrder
  t2_termtype?: Prisma.SortOrder
  wbid?: Prisma.SortOrder
  createtime?: Prisma.SortOrder
}

export type qq_contentSumOrderByAggregateInput = {
  uin?: Prisma.SortOrder
  created_time?: Prisma.SortOrder
  lastmodify?: Prisma.SortOrder
  cmtnum?: Prisma.SortOrder
  fwdnum?: Prisma.SortOrder
  rt_sum?: Prisma.SortOrder
  videototal?: Prisma.SortOrder
  editmask?: Prisma.SortOrder
  right?: Prisma.SortOrder
  ugc_right?: Prisma.SortOrder
  t1_source?: Prisma.SortOrder
  t1_subtype?: Prisma.SortOrder
  t1_termtype?: Prisma.SortOrder
  t2_source?: Prisma.SortOrder
  t2_subtype?: Prisma.SortOrder
  t2_termtype?: Prisma.SortOrder
  wbid?: Prisma.SortOrder
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
}

export type qq_contentSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    tid?: boolean
    uin?: boolean
    name?: boolean
    content?: boolean
    created_time?: boolean
    create_time_str?: boolean
    create_time_str2?: boolean
    lastmodify?: boolean
    source_name?: boolean
    source_url?: boolean
    source_appid?: boolean
    conlist?: boolean
    commentlist?: boolean
    video?: boolean
    lbs?: boolean
    pic?: boolean
    cmtnum?: boolean
    fwdnum?: boolean
    rt_sum?: boolean
    videototal?: boolean
    secret?: boolean
    iseditable?: boolean
    issigin?: boolean
    certified?: boolean
    editmask?: boolean
    has_more_con?: boolean
    right?: boolean
    ugc_right?: boolean
    pic_template?: boolean
    t1_source?: boolean
    t1_subtype?: boolean
    t1_termtype?: boolean
    t2_source?: boolean
    t2_subtype?: boolean
    t2_termtype?: boolean
    wbid?: boolean
    createtime?: boolean
  },
  ExtArgs['result']['qq_content']
>

export type qq_contentSelectScalar = {
  tid?: boolean
  uin?: boolean
  name?: boolean
  content?: boolean
  created_time?: boolean
  create_time_str?: boolean
  create_time_str2?: boolean
  lastmodify?: boolean
  source_name?: boolean
  source_url?: boolean
  source_appid?: boolean
  conlist?: boolean
  commentlist?: boolean
  video?: boolean
  lbs?: boolean
  pic?: boolean
  cmtnum?: boolean
  fwdnum?: boolean
  rt_sum?: boolean
  videototal?: boolean
  secret?: boolean
  iseditable?: boolean
  issigin?: boolean
  certified?: boolean
  editmask?: boolean
  has_more_con?: boolean
  right?: boolean
  ugc_right?: boolean
  pic_template?: boolean
  t1_source?: boolean
  t1_subtype?: boolean
  t1_termtype?: boolean
  t2_source?: boolean
  t2_subtype?: boolean
  t2_termtype?: boolean
  wbid?: boolean
  createtime?: boolean
}

export type qq_contentOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  | 'tid'
  | 'uin'
  | 'name'
  | 'content'
  | 'created_time'
  | 'create_time_str'
  | 'create_time_str2'
  | 'lastmodify'
  | 'source_name'
  | 'source_url'
  | 'source_appid'
  | 'conlist'
  | 'commentlist'
  | 'video'
  | 'lbs'
  | 'pic'
  | 'cmtnum'
  | 'fwdnum'
  | 'rt_sum'
  | 'videototal'
  | 'secret'
  | 'iseditable'
  | 'issigin'
  | 'certified'
  | 'editmask'
  | 'has_more_con'
  | 'right'
  | 'ugc_right'
  | 'pic_template'
  | 't1_source'
  | 't1_subtype'
  | 't1_termtype'
  | 't2_source'
  | 't2_subtype'
  | 't2_termtype'
  | 'wbid'
  | 'createtime',
  ExtArgs['result']['qq_content']
>

export type $qq_contentPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'qq_content'
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      tid: string
      uin: bigint | null
      name: string | null
      content: string | null
      created_time: bigint | null
      create_time_str: string | null
      create_time_str2: string | null
      lastmodify: bigint | null
      source_name: string | null
      source_url: string | null
      source_appid: string | null
      conlist: string | null
      commentlist: string | null
      video: string | null
      lbs: string | null
      pic: string | null
      cmtnum: number | null
      fwdnum: number | null
      rt_sum: number | null
      videototal: number | null
      secret: boolean | null
      iseditable: boolean | null
      issigin: boolean | null
      certified: boolean | null
      editmask: number | null
      has_more_con: boolean | null
      right: number | null
      ugc_right: number | null
      pic_template: string | null
      t1_source: number | null
      t1_subtype: number | null
      t1_termtype: number | null
      t2_source: number | null
      t2_subtype: number | null
      t2_termtype: number | null
      wbid: bigint | null
      createtime: string | null
    },
    ExtArgs['result']['qq_content']
  >
  composites: {}
}

export type qq_contentGetPayload<
  S extends boolean | null | undefined | qq_contentDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$qq_contentPayload, S>

export type qq_contentCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<qq_contentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: Qq_contentCountAggregateInputType | true
}

export interface qq_contentDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['qq_content']
    meta: { name: 'qq_content' }
  }
  /**
   * Find zero or one Qq_content that matches the filter.
   * @param {qq_contentFindUniqueArgs} args - Arguments to find a Qq_content
   * @example
   * // Get one Qq_content
   * const qq_content = await prisma.qq_content.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends qq_contentFindUniqueArgs>(
    args: Prisma.SelectSubset<T, qq_contentFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__qq_contentClient<
    runtime.Types.Result.GetResult<
      Prisma.$qq_contentPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one Qq_content that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {qq_contentFindUniqueOrThrowArgs} args - Arguments to find a Qq_content
   * @example
   * // Get one Qq_content
   * const qq_content = await prisma.qq_content.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends qq_contentFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, qq_contentFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__qq_contentClient<
    runtime.Types.Result.GetResult<
      Prisma.$qq_contentPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Qq_content that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {qq_contentFindFirstArgs} args - Arguments to find a Qq_content
   * @example
   * // Get one Qq_content
   * const qq_content = await prisma.qq_content.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends qq_contentFindFirstArgs>(
    args?: Prisma.SelectSubset<T, qq_contentFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__qq_contentClient<
    runtime.Types.Result.GetResult<
      Prisma.$qq_contentPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first Qq_content that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {qq_contentFindFirstOrThrowArgs} args - Arguments to find a Qq_content
   * @example
   * // Get one Qq_content
   * const qq_content = await prisma.qq_content.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends qq_contentFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, qq_contentFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__qq_contentClient<
    runtime.Types.Result.GetResult<
      Prisma.$qq_contentPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more Qq_contents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {qq_contentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Qq_contents
   * const qq_contents = await prisma.qq_content.findMany()
   *
   * // Get first 10 Qq_contents
   * const qq_contents = await prisma.qq_content.findMany({ take: 10 })
   *
   * // Only select the `tid`
   * const qq_contentWithTidOnly = await prisma.qq_content.findMany({ select: { tid: true } })
   *
   */
  findMany<T extends qq_contentFindManyArgs>(
    args?: Prisma.SelectSubset<T, qq_contentFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$qq_contentPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a Qq_content.
   * @param {qq_contentCreateArgs} args - Arguments to create a Qq_content.
   * @example
   * // Create one Qq_content
   * const Qq_content = await prisma.qq_content.create({
   *   data: {
   *     // ... data to create a Qq_content
   *   }
   * })
   *
   */
  create<T extends qq_contentCreateArgs>(
    args: Prisma.SelectSubset<T, qq_contentCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__qq_contentClient<
    runtime.Types.Result.GetResult<
      Prisma.$qq_contentPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many Qq_contents.
   * @param {qq_contentCreateManyArgs} args - Arguments to create many Qq_contents.
   * @example
   * // Create many Qq_contents
   * const qq_content = await prisma.qq_content.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends qq_contentCreateManyArgs>(
    args?: Prisma.SelectSubset<T, qq_contentCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Qq_content.
   * @param {qq_contentDeleteArgs} args - Arguments to delete one Qq_content.
   * @example
   * // Delete one Qq_content
   * const Qq_content = await prisma.qq_content.delete({
   *   where: {
   *     // ... filter to delete one Qq_content
   *   }
   * })
   *
   */
  delete<T extends qq_contentDeleteArgs>(
    args: Prisma.SelectSubset<T, qq_contentDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__qq_contentClient<
    runtime.Types.Result.GetResult<
      Prisma.$qq_contentPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one Qq_content.
   * @param {qq_contentUpdateArgs} args - Arguments to update one Qq_content.
   * @example
   * // Update one Qq_content
   * const qq_content = await prisma.qq_content.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends qq_contentUpdateArgs>(
    args: Prisma.SelectSubset<T, qq_contentUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__qq_contentClient<
    runtime.Types.Result.GetResult<
      Prisma.$qq_contentPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more Qq_contents.
   * @param {qq_contentDeleteManyArgs} args - Arguments to filter Qq_contents to delete.
   * @example
   * // Delete a few Qq_contents
   * const { count } = await prisma.qq_content.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends qq_contentDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, qq_contentDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Qq_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {qq_contentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Qq_contents
   * const qq_content = await prisma.qq_content.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends qq_contentUpdateManyArgs>(
    args: Prisma.SelectSubset<T, qq_contentUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Qq_content.
   * @param {qq_contentUpsertArgs} args - Arguments to update or create a Qq_content.
   * @example
   * // Update or create a Qq_content
   * const qq_content = await prisma.qq_content.upsert({
   *   create: {
   *     // ... data to create a Qq_content
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Qq_content we want to update
   *   }
   * })
   */
  upsert<T extends qq_contentUpsertArgs>(
    args: Prisma.SelectSubset<T, qq_contentUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__qq_contentClient<
    runtime.Types.Result.GetResult<
      Prisma.$qq_contentPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of Qq_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {qq_contentCountArgs} args - Arguments to filter Qq_contents to count.
   * @example
   * // Count the number of Qq_contents
   * const count = await prisma.qq_content.count({
   *   where: {
   *     // ... the filter for the Qq_contents we want to count
   *   }
   * })
   **/
  count<T extends qq_contentCountArgs>(
    args?: Prisma.Subset<T, qq_contentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Qq_contentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Qq_content.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Qq_contentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends Qq_contentAggregateArgs>(
    args: Prisma.Subset<T, Qq_contentAggregateArgs>,
  ): Prisma.PrismaPromise<GetQq_contentAggregateType<T>>

  /**
   * Group by Qq_content.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {qq_contentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends qq_contentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: qq_contentGroupByArgs['orderBy'] }
      : { orderBy?: qq_contentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    'Field ',
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, qq_contentGroupByArgs, OrderByArg> &
      InputErrors,
  ): {} extends InputErrors
    ? GetQq_contentGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the qq_content model
   */
  readonly fields: qq_contentFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for qq_content.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__qq_contentClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the qq_content model
 */
export interface qq_contentFieldRefs {
  readonly tid: Prisma.FieldRef<'qq_content', 'String'>
  readonly uin: Prisma.FieldRef<'qq_content', 'BigInt'>
  readonly name: Prisma.FieldRef<'qq_content', 'String'>
  readonly content: Prisma.FieldRef<'qq_content', 'String'>
  readonly created_time: Prisma.FieldRef<'qq_content', 'BigInt'>
  readonly create_time_str: Prisma.FieldRef<'qq_content', 'String'>
  readonly create_time_str2: Prisma.FieldRef<'qq_content', 'String'>
  readonly lastmodify: Prisma.FieldRef<'qq_content', 'BigInt'>
  readonly source_name: Prisma.FieldRef<'qq_content', 'String'>
  readonly source_url: Prisma.FieldRef<'qq_content', 'String'>
  readonly source_appid: Prisma.FieldRef<'qq_content', 'String'>
  readonly conlist: Prisma.FieldRef<'qq_content', 'String'>
  readonly commentlist: Prisma.FieldRef<'qq_content', 'String'>
  readonly video: Prisma.FieldRef<'qq_content', 'String'>
  readonly lbs: Prisma.FieldRef<'qq_content', 'String'>
  readonly pic: Prisma.FieldRef<'qq_content', 'String'>
  readonly cmtnum: Prisma.FieldRef<'qq_content', 'Int'>
  readonly fwdnum: Prisma.FieldRef<'qq_content', 'Int'>
  readonly rt_sum: Prisma.FieldRef<'qq_content', 'Int'>
  readonly videototal: Prisma.FieldRef<'qq_content', 'Int'>
  readonly secret: Prisma.FieldRef<'qq_content', 'Boolean'>
  readonly iseditable: Prisma.FieldRef<'qq_content', 'Boolean'>
  readonly issigin: Prisma.FieldRef<'qq_content', 'Boolean'>
  readonly certified: Prisma.FieldRef<'qq_content', 'Boolean'>
  readonly editmask: Prisma.FieldRef<'qq_content', 'Int'>
  readonly has_more_con: Prisma.FieldRef<'qq_content', 'Boolean'>
  readonly right: Prisma.FieldRef<'qq_content', 'Int'>
  readonly ugc_right: Prisma.FieldRef<'qq_content', 'Int'>
  readonly pic_template: Prisma.FieldRef<'qq_content', 'String'>
  readonly t1_source: Prisma.FieldRef<'qq_content', 'Int'>
  readonly t1_subtype: Prisma.FieldRef<'qq_content', 'Int'>
  readonly t1_termtype: Prisma.FieldRef<'qq_content', 'Int'>
  readonly t2_source: Prisma.FieldRef<'qq_content', 'Int'>
  readonly t2_subtype: Prisma.FieldRef<'qq_content', 'Int'>
  readonly t2_termtype: Prisma.FieldRef<'qq_content', 'Int'>
  readonly wbid: Prisma.FieldRef<'qq_content', 'BigInt'>
  readonly createtime: Prisma.FieldRef<'qq_content', 'String'>
}

// Custom InputTypes
/**
 * qq_content findUnique
 */
export type qq_contentFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the qq_content
   */
  select?: Prisma.qq_contentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the qq_content
   */
  omit?: Prisma.qq_contentOmit<ExtArgs> | null
  /**
   * Filter, which qq_content to fetch.
   */
  where: Prisma.qq_contentWhereUniqueInput
}

/**
 * qq_content findUniqueOrThrow
 */
export type qq_contentFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the qq_content
   */
  select?: Prisma.qq_contentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the qq_content
   */
  omit?: Prisma.qq_contentOmit<ExtArgs> | null
  /**
   * Filter, which qq_content to fetch.
   */
  where: Prisma.qq_contentWhereUniqueInput
}

/**
 * qq_content findFirst
 */
export type qq_contentFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the qq_content
   */
  select?: Prisma.qq_contentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the qq_content
   */
  omit?: Prisma.qq_contentOmit<ExtArgs> | null
  /**
   * Filter, which qq_content to fetch.
   */
  where?: Prisma.qq_contentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of qq_contents to fetch.
   */
  orderBy?:
    | Prisma.qq_contentOrderByWithRelationInput
    | Prisma.qq_contentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for qq_contents.
   */
  cursor?: Prisma.qq_contentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` qq_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` qq_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of qq_contents.
   */
  distinct?:
    | Prisma.Qq_contentScalarFieldEnum
    | Prisma.Qq_contentScalarFieldEnum[]
}

/**
 * qq_content findFirstOrThrow
 */
export type qq_contentFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the qq_content
   */
  select?: Prisma.qq_contentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the qq_content
   */
  omit?: Prisma.qq_contentOmit<ExtArgs> | null
  /**
   * Filter, which qq_content to fetch.
   */
  where?: Prisma.qq_contentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of qq_contents to fetch.
   */
  orderBy?:
    | Prisma.qq_contentOrderByWithRelationInput
    | Prisma.qq_contentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for qq_contents.
   */
  cursor?: Prisma.qq_contentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` qq_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` qq_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of qq_contents.
   */
  distinct?:
    | Prisma.Qq_contentScalarFieldEnum
    | Prisma.Qq_contentScalarFieldEnum[]
}

/**
 * qq_content findMany
 */
export type qq_contentFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the qq_content
   */
  select?: Prisma.qq_contentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the qq_content
   */
  omit?: Prisma.qq_contentOmit<ExtArgs> | null
  /**
   * Filter, which qq_contents to fetch.
   */
  where?: Prisma.qq_contentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of qq_contents to fetch.
   */
  orderBy?:
    | Prisma.qq_contentOrderByWithRelationInput
    | Prisma.qq_contentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing qq_contents.
   */
  cursor?: Prisma.qq_contentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` qq_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` qq_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of qq_contents.
   */
  distinct?:
    | Prisma.Qq_contentScalarFieldEnum
    | Prisma.Qq_contentScalarFieldEnum[]
}

/**
 * qq_content create
 */
export type qq_contentCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the qq_content
   */
  select?: Prisma.qq_contentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the qq_content
   */
  omit?: Prisma.qq_contentOmit<ExtArgs> | null
  /**
   * The data needed to create a qq_content.
   */
  data: Prisma.XOR<
    Prisma.qq_contentCreateInput,
    Prisma.qq_contentUncheckedCreateInput
  >
}

/**
 * qq_content createMany
 */
export type qq_contentCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many qq_contents.
   */
  data: Prisma.qq_contentCreateManyInput | Prisma.qq_contentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * qq_content update
 */
export type qq_contentUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the qq_content
   */
  select?: Prisma.qq_contentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the qq_content
   */
  omit?: Prisma.qq_contentOmit<ExtArgs> | null
  /**
   * The data needed to update a qq_content.
   */
  data: Prisma.XOR<
    Prisma.qq_contentUpdateInput,
    Prisma.qq_contentUncheckedUpdateInput
  >
  /**
   * Choose, which qq_content to update.
   */
  where: Prisma.qq_contentWhereUniqueInput
}

/**
 * qq_content updateMany
 */
export type qq_contentUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update qq_contents.
   */
  data: Prisma.XOR<
    Prisma.qq_contentUpdateManyMutationInput,
    Prisma.qq_contentUncheckedUpdateManyInput
  >
  /**
   * Filter which qq_contents to update
   */
  where?: Prisma.qq_contentWhereInput
  /**
   * Limit how many qq_contents to update.
   */
  limit?: number
}

/**
 * qq_content upsert
 */
export type qq_contentUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the qq_content
   */
  select?: Prisma.qq_contentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the qq_content
   */
  omit?: Prisma.qq_contentOmit<ExtArgs> | null
  /**
   * The filter to search for the qq_content to update in case it exists.
   */
  where: Prisma.qq_contentWhereUniqueInput
  /**
   * In case the qq_content found by the `where` argument doesn't exist, create a new qq_content with this data.
   */
  create: Prisma.XOR<
    Prisma.qq_contentCreateInput,
    Prisma.qq_contentUncheckedCreateInput
  >
  /**
   * In case the qq_content was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.qq_contentUpdateInput,
    Prisma.qq_contentUncheckedUpdateInput
  >
}

/**
 * qq_content delete
 */
export type qq_contentDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the qq_content
   */
  select?: Prisma.qq_contentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the qq_content
   */
  omit?: Prisma.qq_contentOmit<ExtArgs> | null
  /**
   * Filter which qq_content to delete.
   */
  where: Prisma.qq_contentWhereUniqueInput
}

/**
 * qq_content deleteMany
 */
export type qq_contentDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which qq_contents to delete
   */
  where?: Prisma.qq_contentWhereInput
  /**
   * Limit how many qq_contents to delete.
   */
  limit?: number
}

/**
 * qq_content without action
 */
export type qq_contentDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the qq_content
   */
  select?: Prisma.qq_contentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the qq_content
   */
  omit?: Prisma.qq_contentOmit<ExtArgs> | null
}
