/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from '@prisma/client/runtime/index-browser'

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal

export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as new (
    secret: never,
  ) => typeof runtime.DbNull,
  JsonNull: runtime.NullTypes.JsonNull as new (
    secret: never,
  ) => typeof runtime.JsonNull,
  AnyNull: runtime.NullTypes.AnyNull as new (
    secret: never,
  ) => typeof runtime.AnyNull,
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull

export const ModelName = {
  blog_comment: 'blog_comment',
  blog_like: 'blog_like',
  blog_view: 'blog_view',
  essay: 'essay',
  qq_content: 'qq_content',
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable',
} as const)

export type TransactionIsolationLevel =
  (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]

export const Blog_commentScalarFieldEnum = {
  id: 'id',
  file_id: 'file_id',
  from_user_id: 'from_user_id',
  to_user_id: 'to_user_id',
  parent_id: 'parent_id',
  depth: 'depth',
  content: 'content',
  from_user_snapshot: 'from_user_snapshot',
  to_user_snapshot: 'to_user_snapshot',
  created_at: 'created_at',
} as const

export type Blog_commentScalarFieldEnum =
  (typeof Blog_commentScalarFieldEnum)[keyof typeof Blog_commentScalarFieldEnum]

export const Blog_likeScalarFieldEnum = {
  id: 'id',
  file_id: 'file_id',
  user_id: 'user_id',
  created_at: 'created_at',
} as const

export type Blog_likeScalarFieldEnum =
  (typeof Blog_likeScalarFieldEnum)[keyof typeof Blog_likeScalarFieldEnum]

export const Blog_viewScalarFieldEnum = {
  id: 'id',
  file_id: 'file_id',
  viewer_id: 'viewer_id',
  user_id: 'user_id',
  created_at: 'created_at',
} as const

export type Blog_viewScalarFieldEnum =
  (typeof Blog_viewScalarFieldEnum)[keyof typeof Blog_viewScalarFieldEnum]

export const EssayScalarFieldEnum = {
  id: 'id',
  content: 'content',
  images: 'images',
  created_at: 'created_at',
  updated_at: 'updated_at',
} as const

export type EssayScalarFieldEnum =
  (typeof EssayScalarFieldEnum)[keyof typeof EssayScalarFieldEnum]

export const Qq_contentScalarFieldEnum = {
  tid: 'tid',
  uin: 'uin',
  name: 'name',
  content: 'content',
  created_time: 'created_time',
  create_time_str: 'create_time_str',
  create_time_str2: 'create_time_str2',
  lastmodify: 'lastmodify',
  source_name: 'source_name',
  source_url: 'source_url',
  source_appid: 'source_appid',
  conlist: 'conlist',
  commentlist: 'commentlist',
  video: 'video',
  lbs: 'lbs',
  pic: 'pic',
  cmtnum: 'cmtnum',
  fwdnum: 'fwdnum',
  rt_sum: 'rt_sum',
  videototal: 'videototal',
  secret: 'secret',
  iseditable: 'iseditable',
  issigin: 'issigin',
  certified: 'certified',
  editmask: 'editmask',
  has_more_con: 'has_more_con',
  right: 'right',
  ugc_right: 'ugc_right',
  pic_template: 'pic_template',
  t1_source: 't1_source',
  t1_subtype: 't1_subtype',
  t1_termtype: 't1_termtype',
  t2_source: 't2_source',
  t2_subtype: 't2_subtype',
  t2_termtype: 't2_termtype',
  wbid: 'wbid',
  createtime: 'createtime',
} as const

export type Qq_contentScalarFieldEnum =
  (typeof Qq_contentScalarFieldEnum)[keyof typeof Qq_contentScalarFieldEnum]

export const SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]

export const JsonNullValueInput = {
  JsonNull: JsonNull,
} as const

export type JsonNullValueInput =
  (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]

export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull,
} as const

export type NullableJsonNullValueInput =
  (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]

export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull,
} as const

export type JsonNullValueFilter =
  (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive',
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]

export const NullsOrder = {
  first: 'first',
  last: 'last',
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

export const blog_commentOrderByRelevanceFieldEnum = {
  id: 'id',
  file_id: 'file_id',
  parent_id: 'parent_id',
} as const

export type blog_commentOrderByRelevanceFieldEnum =
  (typeof blog_commentOrderByRelevanceFieldEnum)[keyof typeof blog_commentOrderByRelevanceFieldEnum]

export const blog_likeOrderByRelevanceFieldEnum = {
  id: 'id',
  file_id: 'file_id',
} as const

export type blog_likeOrderByRelevanceFieldEnum =
  (typeof blog_likeOrderByRelevanceFieldEnum)[keyof typeof blog_likeOrderByRelevanceFieldEnum]

export const blog_viewOrderByRelevanceFieldEnum = {
  id: 'id',
  file_id: 'file_id',
  viewer_id: 'viewer_id',
} as const

export type blog_viewOrderByRelevanceFieldEnum =
  (typeof blog_viewOrderByRelevanceFieldEnum)[keyof typeof blog_viewOrderByRelevanceFieldEnum]

export const essayOrderByRelevanceFieldEnum = {
  id: 'id',
  content: 'content',
} as const

export type essayOrderByRelevanceFieldEnum =
  (typeof essayOrderByRelevanceFieldEnum)[keyof typeof essayOrderByRelevanceFieldEnum]

export const qq_contentOrderByRelevanceFieldEnum = {
  tid: 'tid',
  name: 'name',
  content: 'content',
  create_time_str: 'create_time_str',
  create_time_str2: 'create_time_str2',
  source_name: 'source_name',
  source_url: 'source_url',
  source_appid: 'source_appid',
  conlist: 'conlist',
  commentlist: 'commentlist',
  video: 'video',
  lbs: 'lbs',
  pic: 'pic',
  pic_template: 'pic_template',
  createtime: 'createtime',
} as const

export type qq_contentOrderByRelevanceFieldEnum =
  (typeof qq_contentOrderByRelevanceFieldEnum)[keyof typeof qq_contentOrderByRelevanceFieldEnum]
