/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from '@prisma/client/runtime/client'
import type * as Prisma from '../models.js'
import { type PrismaClient } from './class.js'

export type * from '../models.js'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError =
  runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError =
  runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError =
  runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError =
  runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError =
  runtime.PrismaClientInitializationError
export type PrismaClientInitializationError =
  runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql

/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
 * Extensions
 */
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<
  T,
  F
>
export type Payload<
  T,
  F extends runtime.Operation = never,
> = runtime.Types.Public.Payload<T, F>
export type Result<
  T,
  A,
  F extends runtime.Operation,
> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
export const prismaVersion: PrismaVersion = {
  client: '7.8.0',
  engine: '3c6e192761c0362d496ed980de936e2f3cebcd3a',
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue

export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as new (
    secret: never,
  ) => typeof runtime.DbNull,
  JsonNull: runtime.NullTypes.JsonNull as new (
    secret: never,
  ) => typeof runtime.JsonNull,
  AnyNull: runtime.NullTypes.AnyNull as new (
    secret: never,
  ) => typeof runtime.AnyNull,
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull

type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
  [P in K]: T[P]
}

export type Enumerable<T> = T | Array<T>

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
}

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} & (T extends SelectAndInclude
  ? 'Please either choose `select` or `include`.'
  : T extends SelectAndOmit
    ? 'Please either choose `select` or `omit`.'
    : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} & K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never }

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> = T extends object
  ? U extends object
    ? (Without<T, U> & U) | (Without<U, T> & T)
    : U
  : T

/**
 * Is T a Record?
 */
type IsObject<T extends any> =
  T extends Array<any>
    ? False
    : T extends Date
      ? False
      : T extends Uint8Array
        ? False
        : T extends BigInt
          ? False
          : T extends object
            ? True
            : False

/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<O extends object, K extends Key, strict extends Boolean> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1,
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
  [K in keyof O]: K extends keyof O1 ? O1[K] : O[K]
} & {}

type _Merge<U extends object> = IntersectOf<
  Overwrite<
    U,
    {
      [K in keyof U]-?: At<U, K>
    }
  >
>

type Key = string | number | symbol
type AtStrict<O extends object, K extends Key> = O[K & keyof O]
type AtLoose<O extends object, K extends Key> = O extends unknown
  ? AtStrict<O, K>
  : never
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
  1: AtStrict<O, K>
  0: AtLoose<O, K>
}[strict]

export type ComputeRaw<A extends any> = A extends Function
  ? A
  : {
      [K in keyof A]: A[K]
    } & {}

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K]
} & {}

type _Record<K extends keyof any, T> = {
  [P in K]: T
}

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
    ?
        | (K extends keyof O ? { [P in K]: O[P] } & O : O)
        | ({ [P in keyof O as P extends K ? P : never]-?: O[P] } & O)
    : never
>

type _Strict<U, _U = U> = U extends unknown
  ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>>
  : never

export type Strict<U extends object> = ComputeRaw<_Strict<U>>
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
    ? 1
    : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object
  ? {
      [P in keyof T]: P extends keyof O ? O[P] : never
    }
  : never

type FieldPaths<T, U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>> =
  IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<
          UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never
        >
      : never
    : {} extends FieldPaths<T[K]>
      ? never
      : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<
  T,
  K extends Enumerable<keyof T> | keyof T,
> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}`
  ? never
  : T

export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never
  ? never
  : FieldRef<Model, FieldType>

export const ModelName = {
  blog_comment: 'blog_comment',
  blog_like: 'blog_like',
  blog_view: 'blog_view',
  essay: 'essay',
  qq_content: 'qq_content',
  music_playlist: 'music_playlist',
  music_song: 'music_song',
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils
  .Fn<
  { extArgs: runtime.Types.Extensions.InternalArgs },
  runtime.Types.Utils.Record<string, any>
> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps:
      | 'blog_comment'
      | 'blog_like'
      | 'blog_view'
      | 'essay'
      | 'qq_content'
      | 'music_playlist'
      | 'music_song'
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    blog_comment: {
      payload: Prisma.$blog_commentPayload<ExtArgs>
      fields: Prisma.blog_commentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.blog_commentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_commentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.blog_commentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_commentPayload>
        }
        findFirst: {
          args: Prisma.blog_commentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_commentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.blog_commentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_commentPayload>
        }
        findMany: {
          args: Prisma.blog_commentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_commentPayload>[]
        }
        create: {
          args: Prisma.blog_commentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_commentPayload>
        }
        createMany: {
          args: Prisma.blog_commentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.blog_commentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_commentPayload>
        }
        update: {
          args: Prisma.blog_commentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_commentPayload>
        }
        deleteMany: {
          args: Prisma.blog_commentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.blog_commentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.blog_commentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_commentPayload>
        }
        aggregate: {
          args: Prisma.Blog_commentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBlog_comment>
        }
        groupBy: {
          args: Prisma.blog_commentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Blog_commentGroupByOutputType>[]
        }
        count: {
          args: Prisma.blog_commentCountArgs<ExtArgs>
          result:
            | runtime.Types.Utils.Optional<Prisma.Blog_commentCountAggregateOutputType>
            | number
        }
      }
    }
    blog_like: {
      payload: Prisma.$blog_likePayload<ExtArgs>
      fields: Prisma.blog_likeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.blog_likeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_likePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.blog_likeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_likePayload>
        }
        findFirst: {
          args: Prisma.blog_likeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_likePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.blog_likeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_likePayload>
        }
        findMany: {
          args: Prisma.blog_likeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_likePayload>[]
        }
        create: {
          args: Prisma.blog_likeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_likePayload>
        }
        createMany: {
          args: Prisma.blog_likeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.blog_likeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_likePayload>
        }
        update: {
          args: Prisma.blog_likeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_likePayload>
        }
        deleteMany: {
          args: Prisma.blog_likeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.blog_likeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.blog_likeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_likePayload>
        }
        aggregate: {
          args: Prisma.Blog_likeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBlog_like>
        }
        groupBy: {
          args: Prisma.blog_likeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Blog_likeGroupByOutputType>[]
        }
        count: {
          args: Prisma.blog_likeCountArgs<ExtArgs>
          result:
            | runtime.Types.Utils.Optional<Prisma.Blog_likeCountAggregateOutputType>
            | number
        }
      }
    }
    blog_view: {
      payload: Prisma.$blog_viewPayload<ExtArgs>
      fields: Prisma.blog_viewFieldRefs
      operations: {
        findUnique: {
          args: Prisma.blog_viewFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_viewPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.blog_viewFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_viewPayload>
        }
        findFirst: {
          args: Prisma.blog_viewFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_viewPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.blog_viewFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_viewPayload>
        }
        findMany: {
          args: Prisma.blog_viewFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_viewPayload>[]
        }
        create: {
          args: Prisma.blog_viewCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_viewPayload>
        }
        createMany: {
          args: Prisma.blog_viewCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.blog_viewDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_viewPayload>
        }
        update: {
          args: Prisma.blog_viewUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_viewPayload>
        }
        deleteMany: {
          args: Prisma.blog_viewDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.blog_viewUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.blog_viewUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$blog_viewPayload>
        }
        aggregate: {
          args: Prisma.Blog_viewAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBlog_view>
        }
        groupBy: {
          args: Prisma.blog_viewGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Blog_viewGroupByOutputType>[]
        }
        count: {
          args: Prisma.blog_viewCountArgs<ExtArgs>
          result:
            | runtime.Types.Utils.Optional<Prisma.Blog_viewCountAggregateOutputType>
            | number
        }
      }
    }
    essay: {
      payload: Prisma.$essayPayload<ExtArgs>
      fields: Prisma.essayFieldRefs
      operations: {
        findUnique: {
          args: Prisma.essayFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$essayPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.essayFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$essayPayload>
        }
        findFirst: {
          args: Prisma.essayFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$essayPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.essayFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$essayPayload>
        }
        findMany: {
          args: Prisma.essayFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$essayPayload>[]
        }
        create: {
          args: Prisma.essayCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$essayPayload>
        }
        createMany: {
          args: Prisma.essayCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.essayDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$essayPayload>
        }
        update: {
          args: Prisma.essayUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$essayPayload>
        }
        deleteMany: {
          args: Prisma.essayDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.essayUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.essayUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$essayPayload>
        }
        aggregate: {
          args: Prisma.EssayAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEssay>
        }
        groupBy: {
          args: Prisma.essayGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EssayGroupByOutputType>[]
        }
        count: {
          args: Prisma.essayCountArgs<ExtArgs>
          result:
            | runtime.Types.Utils.Optional<Prisma.EssayCountAggregateOutputType>
            | number
        }
      }
    }
    qq_content: {
      payload: Prisma.$qq_contentPayload<ExtArgs>
      fields: Prisma.qq_contentFieldRefs
      operations: {
        findUnique: {
          args: Prisma.qq_contentFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$qq_contentPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.qq_contentFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$qq_contentPayload>
        }
        findFirst: {
          args: Prisma.qq_contentFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$qq_contentPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.qq_contentFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$qq_contentPayload>
        }
        findMany: {
          args: Prisma.qq_contentFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$qq_contentPayload>[]
        }
        create: {
          args: Prisma.qq_contentCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$qq_contentPayload>
        }
        createMany: {
          args: Prisma.qq_contentCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.qq_contentDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$qq_contentPayload>
        }
        update: {
          args: Prisma.qq_contentUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$qq_contentPayload>
        }
        deleteMany: {
          args: Prisma.qq_contentDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.qq_contentUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.qq_contentUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$qq_contentPayload>
        }
        aggregate: {
          args: Prisma.Qq_contentAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateQq_content>
        }
        groupBy: {
          args: Prisma.qq_contentGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Qq_contentGroupByOutputType>[]
        }
        count: {
          args: Prisma.qq_contentCountArgs<ExtArgs>
          result:
            | runtime.Types.Utils.Optional<Prisma.Qq_contentCountAggregateOutputType>
            | number
        }
      }
    }
    music_playlist: {
      payload: Prisma.$music_playlistPayload<ExtArgs>
      fields: Prisma.music_playlistFieldRefs
      operations: {
        findUnique: {
          args: Prisma.music_playlistFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_playlistPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.music_playlistFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_playlistPayload>
        }
        findFirst: {
          args: Prisma.music_playlistFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_playlistPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.music_playlistFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_playlistPayload>
        }
        findMany: {
          args: Prisma.music_playlistFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_playlistPayload>[]
        }
        create: {
          args: Prisma.music_playlistCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_playlistPayload>
        }
        createMany: {
          args: Prisma.music_playlistCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.music_playlistDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_playlistPayload>
        }
        update: {
          args: Prisma.music_playlistUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_playlistPayload>
        }
        deleteMany: {
          args: Prisma.music_playlistDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.music_playlistUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.music_playlistUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_playlistPayload>
        }
        aggregate: {
          args: Prisma.Music_playlistAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMusic_playlist>
        }
        groupBy: {
          args: Prisma.music_playlistGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Music_playlistGroupByOutputType>[]
        }
        count: {
          args: Prisma.music_playlistCountArgs<ExtArgs>
          result:
            | runtime.Types.Utils.Optional<Prisma.Music_playlistCountAggregateOutputType>
            | number
        }
      }
    }
    music_song: {
      payload: Prisma.$music_songPayload<ExtArgs>
      fields: Prisma.music_songFieldRefs
      operations: {
        findUnique: {
          args: Prisma.music_songFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_songPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.music_songFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_songPayload>
        }
        findFirst: {
          args: Prisma.music_songFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_songPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.music_songFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_songPayload>
        }
        findMany: {
          args: Prisma.music_songFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_songPayload>[]
        }
        create: {
          args: Prisma.music_songCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_songPayload>
        }
        createMany: {
          args: Prisma.music_songCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        delete: {
          args: Prisma.music_songDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_songPayload>
        }
        update: {
          args: Prisma.music_songUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_songPayload>
        }
        deleteMany: {
          args: Prisma.music_songDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.music_songUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        upsert: {
          args: Prisma.music_songUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$music_songPayload>
        }
        aggregate: {
          args: Prisma.Music_songAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMusic_song>
        }
        groupBy: {
          args: Prisma.music_songGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.Music_songGroupByOutputType>[]
        }
        count: {
          args: Prisma.music_songCountArgs<ExtArgs>
          result:
            | runtime.Types.Utils.Optional<Prisma.Music_songCountAggregateOutputType>
            | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]]
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]]
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]]
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]]
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable',
} as const)

export type TransactionIsolationLevel =
  (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]

export const Blog_commentScalarFieldEnum = {
  id: 'id',
  file_id: 'file_id',
  from_user_id: 'from_user_id',
  to_user_id: 'to_user_id',
  parent_id: 'parent_id',
  depth: 'depth',
  content: 'content',
  from_user_snapshot: 'from_user_snapshot',
  to_user_snapshot: 'to_user_snapshot',
  created_at: 'created_at',
} as const

export type Blog_commentScalarFieldEnum =
  (typeof Blog_commentScalarFieldEnum)[keyof typeof Blog_commentScalarFieldEnum]

export const Blog_likeScalarFieldEnum = {
  id: 'id',
  file_id: 'file_id',
  user_id: 'user_id',
  created_at: 'created_at',
} as const

export type Blog_likeScalarFieldEnum =
  (typeof Blog_likeScalarFieldEnum)[keyof typeof Blog_likeScalarFieldEnum]

export const Blog_viewScalarFieldEnum = {
  id: 'id',
  file_id: 'file_id',
  viewer_id: 'viewer_id',
  user_id: 'user_id',
  created_at: 'created_at',
} as const

export type Blog_viewScalarFieldEnum =
  (typeof Blog_viewScalarFieldEnum)[keyof typeof Blog_viewScalarFieldEnum]

export const EssayScalarFieldEnum = {
  id: 'id',
  content: 'content',
  images: 'images',
  created_at: 'created_at',
  updated_at: 'updated_at',
} as const

export type EssayScalarFieldEnum =
  (typeof EssayScalarFieldEnum)[keyof typeof EssayScalarFieldEnum]

export const Qq_contentScalarFieldEnum = {
  tid: 'tid',
  uin: 'uin',
  name: 'name',
  content: 'content',
  created_time: 'created_time',
  create_time_str: 'create_time_str',
  create_time_str2: 'create_time_str2',
  lastmodify: 'lastmodify',
  source_name: 'source_name',
  source_url: 'source_url',
  source_appid: 'source_appid',
  conlist: 'conlist',
  commentlist: 'commentlist',
  video: 'video',
  lbs: 'lbs',
  pic: 'pic',
  cmtnum: 'cmtnum',
  fwdnum: 'fwdnum',
  rt_sum: 'rt_sum',
  videototal: 'videototal',
  secret: 'secret',
  iseditable: 'iseditable',
  issigin: 'issigin',
  certified: 'certified',
  editmask: 'editmask',
  has_more_con: 'has_more_con',
  right: 'right',
  ugc_right: 'ugc_right',
  pic_template: 'pic_template',
  t1_source: 't1_source',
  t1_subtype: 't1_subtype',
  t1_termtype: 't1_termtype',
  t2_source: 't2_source',
  t2_subtype: 't2_subtype',
  t2_termtype: 't2_termtype',
  wbid: 'wbid',
  createtime: 'createtime',
} as const

export type Qq_contentScalarFieldEnum =
  (typeof Qq_contentScalarFieldEnum)[keyof typeof Qq_contentScalarFieldEnum]

export const Music_playlistScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  cover: 'cover',
  sort_order: 'sort_order',
  created_at: 'created_at',
  updated_at: 'updated_at',
} as const

export type Music_playlistScalarFieldEnum =
  (typeof Music_playlistScalarFieldEnum)[keyof typeof Music_playlistScalarFieldEnum]

export const Music_songScalarFieldEnum = {
  id: 'id',
  playlist_id: 'playlist_id',
  title: 'title',
  artist: 'artist',
  album: 'album',
  cover: 'cover',
  source_name: 'source_name',
  source_url: 'source_url',
  sort_order: 'sort_order',
  created_at: 'created_at',
} as const

export type Music_songScalarFieldEnum =
  (typeof Music_songScalarFieldEnum)[keyof typeof Music_songScalarFieldEnum]

export const SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]

export const JsonNullValueInput = {
  JsonNull: JsonNull,
} as const

export type JsonNullValueInput =
  (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]

export const NullableJsonNullValueInput = {
  DbNull: DbNull,
  JsonNull: JsonNull,
} as const

export type NullableJsonNullValueInput =
  (typeof NullableJsonNullValueInput)[keyof typeof NullableJsonNullValueInput]

export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull,
} as const

export type JsonNullValueFilter =
  (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive',
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]

export const NullsOrder = {
  first: 'first',
  last: 'last',
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

export const blog_commentOrderByRelevanceFieldEnum = {
  id: 'id',
  file_id: 'file_id',
  parent_id: 'parent_id',
} as const

export type blog_commentOrderByRelevanceFieldEnum =
  (typeof blog_commentOrderByRelevanceFieldEnum)[keyof typeof blog_commentOrderByRelevanceFieldEnum]

export const blog_likeOrderByRelevanceFieldEnum = {
  id: 'id',
  file_id: 'file_id',
} as const

export type blog_likeOrderByRelevanceFieldEnum =
  (typeof blog_likeOrderByRelevanceFieldEnum)[keyof typeof blog_likeOrderByRelevanceFieldEnum]

export const blog_viewOrderByRelevanceFieldEnum = {
  id: 'id',
  file_id: 'file_id',
  viewer_id: 'viewer_id',
} as const

export type blog_viewOrderByRelevanceFieldEnum =
  (typeof blog_viewOrderByRelevanceFieldEnum)[keyof typeof blog_viewOrderByRelevanceFieldEnum]

export const essayOrderByRelevanceFieldEnum = {
  id: 'id',
  content: 'content',
} as const

export type essayOrderByRelevanceFieldEnum =
  (typeof essayOrderByRelevanceFieldEnum)[keyof typeof essayOrderByRelevanceFieldEnum]

export const qq_contentOrderByRelevanceFieldEnum = {
  tid: 'tid',
  name: 'name',
  content: 'content',
  create_time_str: 'create_time_str',
  create_time_str2: 'create_time_str2',
  source_name: 'source_name',
  source_url: 'source_url',
  source_appid: 'source_appid',
  conlist: 'conlist',
  commentlist: 'commentlist',
  video: 'video',
  lbs: 'lbs',
  pic: 'pic',
  pic_template: 'pic_template',
  createtime: 'createtime',
} as const

export type qq_contentOrderByRelevanceFieldEnum =
  (typeof qq_contentOrderByRelevanceFieldEnum)[keyof typeof qq_contentOrderByRelevanceFieldEnum]

export const music_playlistOrderByRelevanceFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  cover: 'cover',
} as const

export type music_playlistOrderByRelevanceFieldEnum =
  (typeof music_playlistOrderByRelevanceFieldEnum)[keyof typeof music_playlistOrderByRelevanceFieldEnum]

export const music_songOrderByRelevanceFieldEnum = {
  id: 'id',
  playlist_id: 'playlist_id',
  title: 'title',
  artist: 'artist',
  album: 'album',
  cover: 'cover',
  source_name: 'source_name',
  source_url: 'source_url',
} as const

export type music_songOrderByRelevanceFieldEnum =
  (typeof music_songOrderByRelevanceFieldEnum)[keyof typeof music_songOrderByRelevanceFieldEnum]

/**
 * Field references
 */

/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<
  $PrismaModel,
  'String'
>

/**
 * Reference to a field of type 'BigInt'
 */
export type BigIntFieldRefInput<$PrismaModel> = FieldRefInputType<
  $PrismaModel,
  'BigInt'
>

/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<
  $PrismaModel,
  'Int'
>

/**
 * Reference to a field of type 'Json'
 */
export type JsonFieldRefInput<$PrismaModel> = FieldRefInputType<
  $PrismaModel,
  'Json'
>

/**
 * Reference to a field of type 'QueryMode'
 */
export type EnumQueryModeFieldRefInput<$PrismaModel> = FieldRefInputType<
  $PrismaModel,
  'QueryMode'
>

/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<
  $PrismaModel,
  'DateTime'
>

/**
 * Reference to a field of type 'Boolean'
 */
export type BooleanFieldRefInput<$PrismaModel> = FieldRefInputType<
  $PrismaModel,
  'Boolean'
>

/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<
  $PrismaModel,
  'Float'
>

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}

export const defineExtension = runtime.Extensions
  .defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<
  'define',
  TypeMapCb,
  runtime.Types.Extensions.DefaultArgs
>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export type PrismaClientOptions = (
  | {
      /**
       * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
       */
      adapter: runtime.SqlDriverAdapterFactory
      accelerateUrl?: never
    }
  | {
      /**
       * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
       */
      accelerateUrl: string
      adapter?: never
    }
) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   *
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   *
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   *
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Global configuration for omitting model fields by default.
   *
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   *
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[]
  /**
   * Optional maximum size for the query plan cache. If not provided, a default size will be used.
   * A value of `0` can be used to disable the cache entirely. A higher cache size can improve
   * performance for applications that execute a large number of unique queries, while a smaller
   * cache size can reduce memory usage.
   *
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   queryPlanCacheMaxSize: 100,
   * })
   * ```
   */
  queryPlanCacheMaxSize?: number
}
export type GlobalOmitConfig = {
  blog_comment?: Prisma.blog_commentOmit
  blog_like?: Prisma.blog_likeOmit
  blog_view?: Prisma.blog_viewOmit
  essay?: Prisma.essayOmit
  qq_content?: Prisma.qq_contentOmit
  music_playlist?: Prisma.music_playlistOmit
  music_song?: Prisma.music_songOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>

export type GetEvents<T extends any[]> =
  T extends Array<LogLevel | LogDefinition> ? GetLogType<T[number]> : never

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */

export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<
  DefaultPrismaClient,
  runtime.ITXClientDenyList
>
